/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * the Cheque Preview URL.
 */
export type ChequesGetURLResponseBody =
  | UnauthorizedError
  | PermissionMissingError;

/** @internal */
export const ChequesGetURLResponseBody$inboundSchema: z.ZodType<
  ChequesGetURLResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UnauthorizedError$inboundSchema,
  PermissionMissingError$inboundSchema,
]);

/** @internal */
export type ChequesGetURLResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const ChequesGetURLResponseBody$outboundSchema: z.ZodType<
  ChequesGetURLResponseBody$Outbound,
  z.ZodTypeDef,
  ChequesGetURLResponseBody
> = z.union([
  UnauthorizedError$outboundSchema,
  PermissionMissingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesGetURLResponseBody$ {
  /** @deprecated use `ChequesGetURLResponseBody$inboundSchema` instead. */
  export const inboundSchema = ChequesGetURLResponseBody$inboundSchema;
  /** @deprecated use `ChequesGetURLResponseBody$outboundSchema` instead. */
  export const outboundSchema = ChequesGetURLResponseBody$outboundSchema;
  /** @deprecated use `ChequesGetURLResponseBody$Outbound` instead. */
  export type Outbound = ChequesGetURLResponseBody$Outbound;
}

export function chequesGetURLResponseBodyToJSON(
  chequesGetURLResponseBody: ChequesGetURLResponseBody,
): string {
  return JSON.stringify(
    ChequesGetURLResponseBody$outboundSchema.parse(chequesGetURLResponseBody),
  );
}

export function chequesGetURLResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ChequesGetURLResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChequesGetURLResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChequesGetURLResponseBody' from JSON`,
  );
}
