/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * the Cheque.
 */
export type ChequesGetResponseBody = UnauthorizedError | PermissionMissingError;

/** @internal */
export const ChequesGetResponseBody$inboundSchema: z.ZodType<
  ChequesGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UnauthorizedError$inboundSchema,
  PermissionMissingError$inboundSchema,
]);

/** @internal */
export type ChequesGetResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const ChequesGetResponseBody$outboundSchema: z.ZodType<
  ChequesGetResponseBody$Outbound,
  z.ZodTypeDef,
  ChequesGetResponseBody
> = z.union([
  UnauthorizedError$outboundSchema,
  PermissionMissingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesGetResponseBody$ {
  /** @deprecated use `ChequesGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = ChequesGetResponseBody$inboundSchema;
  /** @deprecated use `ChequesGetResponseBody$outboundSchema` instead. */
  export const outboundSchema = ChequesGetResponseBody$outboundSchema;
  /** @deprecated use `ChequesGetResponseBody$Outbound` instead. */
  export type Outbound = ChequesGetResponseBody$Outbound;
}

export function chequesGetResponseBodyToJSON(
  chequesGetResponseBody: ChequesGetResponseBody,
): string {
  return JSON.stringify(
    ChequesGetResponseBody$outboundSchema.parse(chequesGetResponseBody),
  );
}

export function chequesGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ChequesGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChequesGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChequesGetResponseBody' from JSON`,
  );
}
