/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * Cheque object with the depositReadyPDFURL
 */
export type ChequesGetDepositReadyPDFChequesResponseBody =
  | UnauthorizedError
  | PermissionMissingError;

export const ChequesGetDepositReadyPDFObject = {
  Error: "error",
} as const;
export type ChequesGetDepositReadyPDFObject = ClosedEnum<
  typeof ChequesGetDepositReadyPDFObject
>;

export const ChequesGetDepositReadyPDFType = {
  ChequeNotDigitalOnlyError: "cheque_not_digital_only_error",
} as const;
export type ChequesGetDepositReadyPDFType = ClosedEnum<
  typeof ChequesGetDepositReadyPDFType
>;

export const Message = {
  ChequeIsNotDigitalOnly: "Cheque is not digital only",
} as const;
export type Message = ClosedEnum<typeof Message>;

export type ChequesGetDepositReadyPDFError = {
  type: ChequesGetDepositReadyPDFType;
  message: Message;
};

/**
 * Cheque object with the depositReadyPDFURL
 */
export type ChequesGetDepositReadyPDFResponseBodyData = {
  object: ChequesGetDepositReadyPDFObject;
  error: ChequesGetDepositReadyPDFError;
};

/**
 * Cheque object with the depositReadyPDFURL
 */
export class ChequesGetDepositReadyPDFResponseBody extends Error {
  object: ChequesGetDepositReadyPDFObject;
  error: ChequesGetDepositReadyPDFError;

  /** The original data that was passed to this error instance. */
  data$: ChequesGetDepositReadyPDFResponseBodyData;

  constructor(err: ChequesGetDepositReadyPDFResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.object = err.object;
    this.error = err.error;

    this.name = "ChequesGetDepositReadyPDFResponseBody";
  }
}

/** @internal */
export const ChequesGetDepositReadyPDFChequesResponseBody$inboundSchema:
  z.ZodType<
    ChequesGetDepositReadyPDFChequesResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.union([
    UnauthorizedError$inboundSchema,
    PermissionMissingError$inboundSchema,
  ]);

/** @internal */
export type ChequesGetDepositReadyPDFChequesResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const ChequesGetDepositReadyPDFChequesResponseBody$outboundSchema:
  z.ZodType<
    ChequesGetDepositReadyPDFChequesResponseBody$Outbound,
    z.ZodTypeDef,
    ChequesGetDepositReadyPDFChequesResponseBody
  > = z.union([
    UnauthorizedError$outboundSchema,
    PermissionMissingError$outboundSchema,
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesGetDepositReadyPDFChequesResponseBody$ {
  /** @deprecated use `ChequesGetDepositReadyPDFChequesResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    ChequesGetDepositReadyPDFChequesResponseBody$inboundSchema;
  /** @deprecated use `ChequesGetDepositReadyPDFChequesResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    ChequesGetDepositReadyPDFChequesResponseBody$outboundSchema;
  /** @deprecated use `ChequesGetDepositReadyPDFChequesResponseBody$Outbound` instead. */
  export type Outbound = ChequesGetDepositReadyPDFChequesResponseBody$Outbound;
}

export function chequesGetDepositReadyPDFChequesResponseBodyToJSON(
  chequesGetDepositReadyPDFChequesResponseBody:
    ChequesGetDepositReadyPDFChequesResponseBody,
): string {
  return JSON.stringify(
    ChequesGetDepositReadyPDFChequesResponseBody$outboundSchema.parse(
      chequesGetDepositReadyPDFChequesResponseBody,
    ),
  );
}

export function chequesGetDepositReadyPDFChequesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ChequesGetDepositReadyPDFChequesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChequesGetDepositReadyPDFChequesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ChequesGetDepositReadyPDFChequesResponseBody' from JSON`,
  );
}

/** @internal */
export const ChequesGetDepositReadyPDFObject$inboundSchema: z.ZodNativeEnum<
  typeof ChequesGetDepositReadyPDFObject
> = z.nativeEnum(ChequesGetDepositReadyPDFObject);

/** @internal */
export const ChequesGetDepositReadyPDFObject$outboundSchema: z.ZodNativeEnum<
  typeof ChequesGetDepositReadyPDFObject
> = ChequesGetDepositReadyPDFObject$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesGetDepositReadyPDFObject$ {
  /** @deprecated use `ChequesGetDepositReadyPDFObject$inboundSchema` instead. */
  export const inboundSchema = ChequesGetDepositReadyPDFObject$inboundSchema;
  /** @deprecated use `ChequesGetDepositReadyPDFObject$outboundSchema` instead. */
  export const outboundSchema = ChequesGetDepositReadyPDFObject$outboundSchema;
}

/** @internal */
export const ChequesGetDepositReadyPDFType$inboundSchema: z.ZodNativeEnum<
  typeof ChequesGetDepositReadyPDFType
> = z.nativeEnum(ChequesGetDepositReadyPDFType);

/** @internal */
export const ChequesGetDepositReadyPDFType$outboundSchema: z.ZodNativeEnum<
  typeof ChequesGetDepositReadyPDFType
> = ChequesGetDepositReadyPDFType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesGetDepositReadyPDFType$ {
  /** @deprecated use `ChequesGetDepositReadyPDFType$inboundSchema` instead. */
  export const inboundSchema = ChequesGetDepositReadyPDFType$inboundSchema;
  /** @deprecated use `ChequesGetDepositReadyPDFType$outboundSchema` instead. */
  export const outboundSchema = ChequesGetDepositReadyPDFType$outboundSchema;
}

/** @internal */
export const Message$inboundSchema: z.ZodNativeEnum<typeof Message> = z
  .nativeEnum(Message);

/** @internal */
export const Message$outboundSchema: z.ZodNativeEnum<typeof Message> =
  Message$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Message$ {
  /** @deprecated use `Message$inboundSchema` instead. */
  export const inboundSchema = Message$inboundSchema;
  /** @deprecated use `Message$outboundSchema` instead. */
  export const outboundSchema = Message$outboundSchema;
}

/** @internal */
export const ChequesGetDepositReadyPDFError$inboundSchema: z.ZodType<
  ChequesGetDepositReadyPDFError,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: ChequesGetDepositReadyPDFType$inboundSchema,
  message: Message$inboundSchema,
});

/** @internal */
export type ChequesGetDepositReadyPDFError$Outbound = {
  type: string;
  message: string;
};

/** @internal */
export const ChequesGetDepositReadyPDFError$outboundSchema: z.ZodType<
  ChequesGetDepositReadyPDFError$Outbound,
  z.ZodTypeDef,
  ChequesGetDepositReadyPDFError
> = z.object({
  type: ChequesGetDepositReadyPDFType$outboundSchema,
  message: Message$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesGetDepositReadyPDFError$ {
  /** @deprecated use `ChequesGetDepositReadyPDFError$inboundSchema` instead. */
  export const inboundSchema = ChequesGetDepositReadyPDFError$inboundSchema;
  /** @deprecated use `ChequesGetDepositReadyPDFError$outboundSchema` instead. */
  export const outboundSchema = ChequesGetDepositReadyPDFError$outboundSchema;
  /** @deprecated use `ChequesGetDepositReadyPDFError$Outbound` instead. */
  export type Outbound = ChequesGetDepositReadyPDFError$Outbound;
}

export function chequesGetDepositReadyPDFErrorToJSON(
  chequesGetDepositReadyPDFError: ChequesGetDepositReadyPDFError,
): string {
  return JSON.stringify(
    ChequesGetDepositReadyPDFError$outboundSchema.parse(
      chequesGetDepositReadyPDFError,
    ),
  );
}

export function chequesGetDepositReadyPDFErrorFromJSON(
  jsonString: string,
): SafeParseResult<ChequesGetDepositReadyPDFError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChequesGetDepositReadyPDFError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChequesGetDepositReadyPDFError' from JSON`,
  );
}

/** @internal */
export const ChequesGetDepositReadyPDFResponseBody$inboundSchema: z.ZodType<
  ChequesGetDepositReadyPDFResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ChequesGetDepositReadyPDFObject$inboundSchema,
  error: z.lazy(() => ChequesGetDepositReadyPDFError$inboundSchema),
})
  .transform((v) => {
    return new ChequesGetDepositReadyPDFResponseBody(v);
  });

/** @internal */
export type ChequesGetDepositReadyPDFResponseBody$Outbound = {
  object: string;
  error: ChequesGetDepositReadyPDFError$Outbound;
};

/** @internal */
export const ChequesGetDepositReadyPDFResponseBody$outboundSchema: z.ZodType<
  ChequesGetDepositReadyPDFResponseBody$Outbound,
  z.ZodTypeDef,
  ChequesGetDepositReadyPDFResponseBody
> = z.instanceof(ChequesGetDepositReadyPDFResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    object: ChequesGetDepositReadyPDFObject$outboundSchema,
    error: z.lazy(() => ChequesGetDepositReadyPDFError$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesGetDepositReadyPDFResponseBody$ {
  /** @deprecated use `ChequesGetDepositReadyPDFResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    ChequesGetDepositReadyPDFResponseBody$inboundSchema;
  /** @deprecated use `ChequesGetDepositReadyPDFResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    ChequesGetDepositReadyPDFResponseBody$outboundSchema;
  /** @deprecated use `ChequesGetDepositReadyPDFResponseBody$Outbound` instead. */
  export type Outbound = ChequesGetDepositReadyPDFResponseBody$Outbound;
}
