/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * Access is unauthorized.
 */
export type ContactsGetResponseBody =
  | UnauthorizedError
  | PermissionMissingError;

/** @internal */
export const ContactsGetResponseBody$inboundSchema: z.ZodType<
  ContactsGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UnauthorizedError$inboundSchema,
  PermissionMissingError$inboundSchema,
]);

/** @internal */
export type ContactsGetResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const ContactsGetResponseBody$outboundSchema: z.ZodType<
  ContactsGetResponseBody$Outbound,
  z.ZodTypeDef,
  ContactsGetResponseBody
> = z.union([
  UnauthorizedError$outboundSchema,
  PermissionMissingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContactsGetResponseBody$ {
  /** @deprecated use `ContactsGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = ContactsGetResponseBody$inboundSchema;
  /** @deprecated use `ContactsGetResponseBody$outboundSchema` instead. */
  export const outboundSchema = ContactsGetResponseBody$outboundSchema;
  /** @deprecated use `ContactsGetResponseBody$Outbound` instead. */
  export type Outbound = ContactsGetResponseBody$Outbound;
}

export function contactsGetResponseBodyToJSON(
  contactsGetResponseBody: ContactsGetResponseBody,
): string {
  return JSON.stringify(
    ContactsGetResponseBody$outboundSchema.parse(contactsGetResponseBody),
  );
}

export function contactsGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ContactsGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactsGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactsGetResponseBody' from JSON`,
  );
}
