/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * the Letter.
 */
export type LettersGetResponseBody = UnauthorizedError | PermissionMissingError;

/** @internal */
export const LettersGetResponseBody$inboundSchema: z.ZodType<
  LettersGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UnauthorizedError$inboundSchema,
  PermissionMissingError$inboundSchema,
]);

/** @internal */
export type LettersGetResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const LettersGetResponseBody$outboundSchema: z.ZodType<
  LettersGetResponseBody$Outbound,
  z.ZodTypeDef,
  LettersGetResponseBody
> = z.union([
  UnauthorizedError$outboundSchema,
  PermissionMissingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LettersGetResponseBody$ {
  /** @deprecated use `LettersGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = LettersGetResponseBody$inboundSchema;
  /** @deprecated use `LettersGetResponseBody$outboundSchema` instead. */
  export const outboundSchema = LettersGetResponseBody$outboundSchema;
  /** @deprecated use `LettersGetResponseBody$Outbound` instead. */
  export type Outbound = LettersGetResponseBody$Outbound;
}

export function lettersGetResponseBodyToJSON(
  lettersGetResponseBody: LettersGetResponseBody,
): string {
  return JSON.stringify(
    LettersGetResponseBody$outboundSchema.parse(lettersGetResponseBody),
  );
}

export function lettersGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<LettersGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LettersGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LettersGetResponseBody' from JSON`,
  );
}
