/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * the Letter Preview URL.
 */
export type LettersGetURLResponseBody =
  | UnauthorizedError
  | PermissionMissingError;

/** @internal */
export const LettersGetURLResponseBody$inboundSchema: z.ZodType<
  LettersGetURLResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UnauthorizedError$inboundSchema,
  PermissionMissingError$inboundSchema,
]);

/** @internal */
export type LettersGetURLResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const LettersGetURLResponseBody$outboundSchema: z.ZodType<
  LettersGetURLResponseBody$Outbound,
  z.ZodTypeDef,
  LettersGetURLResponseBody
> = z.union([
  UnauthorizedError$outboundSchema,
  PermissionMissingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LettersGetURLResponseBody$ {
  /** @deprecated use `LettersGetURLResponseBody$inboundSchema` instead. */
  export const inboundSchema = LettersGetURLResponseBody$inboundSchema;
  /** @deprecated use `LettersGetURLResponseBody$outboundSchema` instead. */
  export const outboundSchema = LettersGetURLResponseBody$outboundSchema;
  /** @deprecated use `LettersGetURLResponseBody$Outbound` instead. */
  export type Outbound = LettersGetURLResponseBody$Outbound;
}

export function lettersGetURLResponseBodyToJSON(
  lettersGetURLResponseBody: LettersGetURLResponseBody,
): string {
  return JSON.stringify(
    LettersGetURLResponseBody$outboundSchema.parse(lettersGetURLResponseBody),
  );
}

export function lettersGetURLResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<LettersGetURLResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LettersGetURLResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LettersGetURLResponseBody' from JSON`,
  );
}
