/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * the Postcard Preview URL.
 */
export type PostcardsGetURLResponseBody =
  | UnauthorizedError
  | PermissionMissingError;

/** @internal */
export const PostcardsGetURLResponseBody$inboundSchema: z.ZodType<
  PostcardsGetURLResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UnauthorizedError$inboundSchema,
  PermissionMissingError$inboundSchema,
]);

/** @internal */
export type PostcardsGetURLResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const PostcardsGetURLResponseBody$outboundSchema: z.ZodType<
  PostcardsGetURLResponseBody$Outbound,
  z.ZodTypeDef,
  PostcardsGetURLResponseBody
> = z.union([
  UnauthorizedError$outboundSchema,
  PermissionMissingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardsGetURLResponseBody$ {
  /** @deprecated use `PostcardsGetURLResponseBody$inboundSchema` instead. */
  export const inboundSchema = PostcardsGetURLResponseBody$inboundSchema;
  /** @deprecated use `PostcardsGetURLResponseBody$outboundSchema` instead. */
  export const outboundSchema = PostcardsGetURLResponseBody$outboundSchema;
  /** @deprecated use `PostcardsGetURLResponseBody$Outbound` instead. */
  export type Outbound = PostcardsGetURLResponseBody$Outbound;
}

export function postcardsGetURLResponseBodyToJSON(
  postcardsGetURLResponseBody: PostcardsGetURLResponseBody,
): string {
  return JSON.stringify(
    PostcardsGetURLResponseBody$outboundSchema.parse(
      postcardsGetURLResponseBody,
    ),
  );
}

export function postcardsGetURLResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostcardsGetURLResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardsGetURLResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardsGetURLResponseBody' from JSON`,
  );
}
