/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * the Postcard.
 */
export type PostcardsGetResponseBody =
  | UnauthorizedError
  | PermissionMissingError;

/** @internal */
export const PostcardsGetResponseBody$inboundSchema: z.ZodType<
  PostcardsGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UnauthorizedError$inboundSchema,
  PermissionMissingError$inboundSchema,
]);

/** @internal */
export type PostcardsGetResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const PostcardsGetResponseBody$outboundSchema: z.ZodType<
  PostcardsGetResponseBody$Outbound,
  z.ZodTypeDef,
  PostcardsGetResponseBody
> = z.union([
  UnauthorizedError$outboundSchema,
  PermissionMissingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardsGetResponseBody$ {
  /** @deprecated use `PostcardsGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = PostcardsGetResponseBody$inboundSchema;
  /** @deprecated use `PostcardsGetResponseBody$outboundSchema` instead. */
  export const outboundSchema = PostcardsGetResponseBody$outboundSchema;
  /** @deprecated use `PostcardsGetResponseBody$Outbound` instead. */
  export type Outbound = PostcardsGetResponseBody$Outbound;
}

export function postcardsGetResponseBodyToJSON(
  postcardsGetResponseBody: PostcardsGetResponseBody,
): string {
  return JSON.stringify(
    PostcardsGetResponseBody$outboundSchema.parse(postcardsGetResponseBody),
  );
}

export function postcardsGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostcardsGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardsGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardsGetResponseBody' from JSON`,
  );
}
