/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  PermissionMissingError,
  PermissionMissingError$inboundSchema,
  PermissionMissingError$Outbound,
  PermissionMissingError$outboundSchema,
} from "./permissionmissingerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UnauthorizedError,
  UnauthorizedError$inboundSchema,
  UnauthorizedError$Outbound,
  UnauthorizedError$outboundSchema,
} from "./unauthorizederror.js";

/**
 * the Self-Mailer.
 */
export type SelfMailersGetResponseBody =
  | UnauthorizedError
  | PermissionMissingError;

/** @internal */
export const SelfMailersGetResponseBody$inboundSchema: z.ZodType<
  SelfMailersGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UnauthorizedError$inboundSchema,
  PermissionMissingError$inboundSchema,
]);

/** @internal */
export type SelfMailersGetResponseBody$Outbound =
  | UnauthorizedError$Outbound
  | PermissionMissingError$Outbound;

/** @internal */
export const SelfMailersGetResponseBody$outboundSchema: z.ZodType<
  SelfMailersGetResponseBody$Outbound,
  z.ZodTypeDef,
  SelfMailersGetResponseBody
> = z.union([
  UnauthorizedError$outboundSchema,
  PermissionMissingError$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailersGetResponseBody$ {
  /** @deprecated use `SelfMailersGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = SelfMailersGetResponseBody$inboundSchema;
  /** @deprecated use `SelfMailersGetResponseBody$outboundSchema` instead. */
  export const outboundSchema = SelfMailersGetResponseBody$outboundSchema;
  /** @deprecated use `SelfMailersGetResponseBody$Outbound` instead. */
  export type Outbound = SelfMailersGetResponseBody$Outbound;
}

export function selfMailersGetResponseBodyToJSON(
  selfMailersGetResponseBody: SelfMailersGetResponseBody,
): string {
  return JSON.stringify(
    SelfMailersGetResponseBody$outboundSchema.parse(selfMailersGetResponseBody),
  );
}

export function selfMailersGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailersGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailersGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailersGetResponseBody' from JSON`,
  );
}
