/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { bankAccountsCreate } from "../../funcs/bankAccountsCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.BankAccountCreate$inboundSchema,
};

export const tool$bankAccountsCreate: ToolDefinition<typeof args> = {
  name: "bank-accounts-create",
  description: `Create Bank Account

Create a bank account. A US bank account is created by setting \`bankCountryCode\` to \`US\` and providing \`accountNumber\` and \`routingNumber\`. A canadian bank account can be created by specifying \`bankCountryCode\` as \`CA\` and setting \`accountNumber\`, \`routeNumber\`, and \`transitNumber\` accordingly.

You must specify _either_ \`signatureImage\` or \`signatureText\`. The image can be supplied as either a URL or a multipart file upload.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await bankAccountsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
