/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { boxesDelete } from "../../funcs/boxesDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.BoxesDeleteRequest$inboundSchema,
};

export const tool$boxesDelete: ToolDefinition<typeof args> = {
  name: "boxes-delete",
  description: `Cancel Box

Cancel a box by ID (cannot be undone).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await boxesDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
