/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { boxesCreate } from "../../funcs/boxesCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.BoxCreate$inboundSchema,
};

export const tool$boxesCreate: ToolDefinition<typeof args> = {
  name: "boxes-create",
  description: `Create Box

This endpoint allows you to create a box containing up to 100 cheques. 
A Box is mailed to a single destination.

To create a box. You must specify:
- \`to\`: The recipient (contact or contact ID)
- \`from\`: The sender (contact or contact ID)
- \`cheques\`: An array of cheques to go in the box

For each cheque You must specify:
- \`to\`: The recipient (contact or contact ID)
- \`from\`: The sender (contact or contact ID)
- \`bankAccount\`: The bank account ID
- \`amount\`: The amount to be sent
- \`number\`: The cheque number`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await boxesCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
