/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactsList } from "../../funcs/contactsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ContactsListRequest$inboundSchema,
};

export const tool$contactsList: ToolDefinition<typeof args> = {
  name: "contacts-list",
  description: `List Contacts

Get a list of contacts.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await contactsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
