/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lettersList } from "../../funcs/lettersList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.LettersListRequest$inboundSchema,
};

export const tool$lettersList: ToolDefinition<typeof args> = {
  name: "letters-list",
  description: `List Letters

Get a list of letters.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await lettersList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
