/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postcardsDelete } from "../../funcs/postcardsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostcardsDeleteRequest$inboundSchema,
};

export const tool$postcardsDelete: ToolDefinition<typeof args> = {
  name: "postcards-delete",
  description: `Cancel Postcard

Cancel a postcard by ID. Note that this operation cannot be undone.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await postcardsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
