/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postcardsGetUrl } from "../../funcs/postcardsGetUrl.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostcardsGetURLRequest$inboundSchema,
};

export const tool$postcardsGetUrl: ToolDefinition<typeof args> = {
  name: "postcards-get-url",
  description: `Get Postcard Preview

Retrieve a postcard preview URL.

This is only available for customers with our document management addon, which offers
document generation and hosting capabilities. This endpoint has a much higher rate limit
than the regular order retrieval endpoint, so it is suitable for customer-facing use-cases.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await postcardsGetUrl(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
