/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postcardsList } from "../../funcs/postcardsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostcardsListRequest$inboundSchema,
};

export const tool$postcardsList: ToolDefinition<typeof args> = {
  name: "postcards-list",
  description: `List Postcards

Get a list of postcards.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await postcardsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
