/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { selfMailersGet } from "../../funcs/selfMailersGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SelfMailersGetRequest$inboundSchema,
};

export const tool$selfMailersGet: ToolDefinition<typeof args> = {
  name: "self-mailers-get",
  description: `Get Self Mailer

Retrieve a self-mailer by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await selfMailersGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
