/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { selfMailersList } from "../../funcs/selfMailersList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SelfMailersListRequest$inboundSchema,
};

export const tool$selfMailersList: ToolDefinition<typeof args> = {
  name: "self-mailers-list",
  description: `List Self Mailers

Get a list of self-mailers.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await selfMailersList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
