/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { templatesCreate } from "../../funcs/templatesCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.TemplateCreate$inboundSchema,
};

export const tool$templatesCreate: ToolDefinition<typeof args> = {
  name: "templates-create",
  description: `Create Template

Create a template. Note that if you want to create a template that works with our template editor, you must use our dashboard.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await templatesCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
