/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { BankAccounts } from "./bankaccounts.js";
import { Boxes } from "./boxes.js";
import { Cheques } from "./cheques.js";
import { Contacts } from "./contacts.js";
import { Letters } from "./letters.js";
import { Postcards } from "./postcards.js";
import { SelfMailers } from "./selfmailers.js";
import { Templates } from "./templates.js";

export class PostGrid extends ClientSDK {
  private _bankAccounts?: BankAccounts;
  get bankAccounts(): BankAccounts {
    return (this._bankAccounts ??= new BankAccounts(this._options));
  }

  private _boxes?: Boxes;
  get boxes(): Boxes {
    return (this._boxes ??= new Boxes(this._options));
  }

  private _cheques?: Cheques;
  get cheques(): Cheques {
    return (this._cheques ??= new Cheques(this._options));
  }

  private _contacts?: Contacts;
  get contacts(): Contacts {
    return (this._contacts ??= new Contacts(this._options));
  }

  private _letters?: Letters;
  get letters(): Letters {
    return (this._letters ??= new Letters(this._options));
  }

  private _postcards?: Postcards;
  get postcards(): Postcards {
    return (this._postcards ??= new Postcards(this._options));
  }

  private _selfMailers?: SelfMailers;
  get selfMailers(): SelfMailers {
    return (this._selfMailers ??= new SelfMailers(this._options));
  }

  private _templates?: Templates;
  get templates(): Templates {
    return (this._templates ??= new Templates(this._options));
  }
}
