workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    PostGrid Print & Mail API:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/postgrid/postgrid/post-grid-print-&-mail-api
targets:
    postgrid:
        target: typescript
        source: PostGrid Print & Mail API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/postgrid/postgrid/post-grid-print-&-mail-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
