/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BoxesGetRequest = {
  /**
   * The ID of the box to retrieve.
   */
  id: string;
};

/** @internal */
export const BoxesGetRequest$inboundSchema: z.ZodType<
  BoxesGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type BoxesGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const BoxesGetRequest$outboundSchema: z.ZodType<
  BoxesGetRequest$Outbound,
  z.ZodTypeDef,
  BoxesGetRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BoxesGetRequest$ {
  /** @deprecated use `BoxesGetRequest$inboundSchema` instead. */
  export const inboundSchema = BoxesGetRequest$inboundSchema;
  /** @deprecated use `BoxesGetRequest$outboundSchema` instead. */
  export const outboundSchema = BoxesGetRequest$outboundSchema;
  /** @deprecated use `BoxesGetRequest$Outbound` instead. */
  export type Outbound = BoxesGetRequest$Outbound;
}

export function boxesGetRequestToJSON(
  boxesGetRequest: BoxesGetRequest,
): string {
  return JSON.stringify(BoxesGetRequest$outboundSchema.parse(boxesGetRequest));
}

export function boxesGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<BoxesGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BoxesGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BoxesGetRequest' from JSON`,
  );
}
