/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ChequesListRequest = {
  skip?: number | undefined;
  limit?: number | undefined;
  /**
   * You can supply any string to help narrow down the list of resources. For example, if you pass `"New York"` (quoted), it will return resources that have that string present somewhere in their response. Alternatively, you can supply a structured search query. See the documentation on `StructuredSearchQuery` for more details.
   */
  search?: string | undefined;
};

/** @internal */
export const ChequesListRequest$inboundSchema: z.ZodType<
  ChequesListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  skip: z.number().int().default(0),
  limit: z.number().int().default(10),
  search: z.string().optional(),
});

/** @internal */
export type ChequesListRequest$Outbound = {
  skip: number;
  limit: number;
  search?: string | undefined;
};

/** @internal */
export const ChequesListRequest$outboundSchema: z.ZodType<
  ChequesListRequest$Outbound,
  z.ZodTypeDef,
  ChequesListRequest
> = z.object({
  skip: z.number().int().default(0),
  limit: z.number().int().default(10),
  search: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesListRequest$ {
  /** @deprecated use `ChequesListRequest$inboundSchema` instead. */
  export const inboundSchema = ChequesListRequest$inboundSchema;
  /** @deprecated use `ChequesListRequest$outboundSchema` instead. */
  export const outboundSchema = ChequesListRequest$outboundSchema;
  /** @deprecated use `ChequesListRequest$Outbound` instead. */
  export type Outbound = ChequesListRequest$Outbound;
}

export function chequesListRequestToJSON(
  chequesListRequest: ChequesListRequest,
): string {
  return JSON.stringify(
    ChequesListRequest$outboundSchema.parse(chequesListRequest),
  );
}

export function chequesListRequestFromJSON(
  jsonString: string,
): SafeParseResult<ChequesListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChequesListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChequesListRequest' from JSON`,
  );
}
