/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ChequesGetRequest = {
  /**
   * The ID of the cheque to retrieve.
   */
  id: string;
};

/** @internal */
export const ChequesGetRequest$inboundSchema: z.ZodType<
  ChequesGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type ChequesGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const ChequesGetRequest$outboundSchema: z.ZodType<
  ChequesGetRequest$Outbound,
  z.ZodTypeDef,
  ChequesGetRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesGetRequest$ {
  /** @deprecated use `ChequesGetRequest$inboundSchema` instead. */
  export const inboundSchema = ChequesGetRequest$inboundSchema;
  /** @deprecated use `ChequesGetRequest$outboundSchema` instead. */
  export const outboundSchema = ChequesGetRequest$outboundSchema;
  /** @deprecated use `ChequesGetRequest$Outbound` instead. */
  export type Outbound = ChequesGetRequest$Outbound;
}

export function chequesGetRequestToJSON(
  chequesGetRequest: ChequesGetRequest,
): string {
  return JSON.stringify(
    ChequesGetRequest$outboundSchema.parse(chequesGetRequest),
  );
}

export function chequesGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<ChequesGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChequesGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChequesGetRequest' from JSON`,
  );
}
