/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ChequesDeleteRequest = {
  /**
   * The ID of the cheque you want to cancel.
   */
  id: string;
};

/** @internal */
export const ChequesDeleteRequest$inboundSchema: z.ZodType<
  ChequesDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type ChequesDeleteRequest$Outbound = {
  id: string;
};

/** @internal */
export const ChequesDeleteRequest$outboundSchema: z.ZodType<
  ChequesDeleteRequest$Outbound,
  z.ZodTypeDef,
  ChequesDeleteRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChequesDeleteRequest$ {
  /** @deprecated use `ChequesDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = ChequesDeleteRequest$inboundSchema;
  /** @deprecated use `ChequesDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = ChequesDeleteRequest$outboundSchema;
  /** @deprecated use `ChequesDeleteRequest$Outbound` instead. */
  export type Outbound = ChequesDeleteRequest$Outbound;
}

export function chequesDeleteRequestToJSON(
  chequesDeleteRequest: ChequesDeleteRequest,
): string {
  return JSON.stringify(
    ChequesDeleteRequest$outboundSchema.parse(chequesDeleteRequest),
  );
}

export function chequesDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<ChequesDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChequesDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChequesDeleteRequest' from JSON`,
  );
}
