/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ContactsGetRequest = {
  id: string;
};

/** @internal */
export const ContactsGetRequest$inboundSchema: z.ZodType<
  ContactsGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type ContactsGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const ContactsGetRequest$outboundSchema: z.ZodType<
  ContactsGetRequest$Outbound,
  z.ZodTypeDef,
  ContactsGetRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContactsGetRequest$ {
  /** @deprecated use `ContactsGetRequest$inboundSchema` instead. */
  export const inboundSchema = ContactsGetRequest$inboundSchema;
  /** @deprecated use `ContactsGetRequest$outboundSchema` instead. */
  export const outboundSchema = ContactsGetRequest$outboundSchema;
  /** @deprecated use `ContactsGetRequest$Outbound` instead. */
  export type Outbound = ContactsGetRequest$Outbound;
}

export function contactsGetRequestToJSON(
  contactsGetRequest: ContactsGetRequest,
): string {
  return JSON.stringify(
    ContactsGetRequest$outboundSchema.parse(contactsGetRequest),
  );
}

export function contactsGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<ContactsGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactsGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactsGetRequest' from JSON`,
  );
}
