/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LettersListRequest = {
  skip?: number | undefined;
  limit?: number | undefined;
  /**
   * You can supply any string to help narrow down the list of resources. For example, if you pass `"New York"` (quoted), it will return resources that have that string present somewhere in their response. Alternatively, you can supply a structured search query. See the documentation on `StructuredSearchQuery` for more details.
   */
  search?: string | undefined;
};

/** @internal */
export const LettersListRequest$inboundSchema: z.ZodType<
  LettersListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  skip: z.number().int().default(0),
  limit: z.number().int().default(10),
  search: z.string().optional(),
});

/** @internal */
export type LettersListRequest$Outbound = {
  skip: number;
  limit: number;
  search?: string | undefined;
};

/** @internal */
export const LettersListRequest$outboundSchema: z.ZodType<
  LettersListRequest$Outbound,
  z.ZodTypeDef,
  LettersListRequest
> = z.object({
  skip: z.number().int().default(0),
  limit: z.number().int().default(10),
  search: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LettersListRequest$ {
  /** @deprecated use `LettersListRequest$inboundSchema` instead. */
  export const inboundSchema = LettersListRequest$inboundSchema;
  /** @deprecated use `LettersListRequest$outboundSchema` instead. */
  export const outboundSchema = LettersListRequest$outboundSchema;
  /** @deprecated use `LettersListRequest$Outbound` instead. */
  export type Outbound = LettersListRequest$Outbound;
}

export function lettersListRequestToJSON(
  lettersListRequest: LettersListRequest,
): string {
  return JSON.stringify(
    LettersListRequest$outboundSchema.parse(lettersListRequest),
  );
}

export function lettersListRequestFromJSON(
  jsonString: string,
): SafeParseResult<LettersListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LettersListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LettersListRequest' from JSON`,
  );
}
