/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostcardsGetURLRequest = {
  /**
   * The ID of the postcard to retrieve the preview URL for.
   */
  id: string;
};

/**
 * the Postcard Preview URL.
 */
export type PostcardsGetURLResponseBody = {
  /**
   * A unique ID prefixed with postcard_
   */
  id: string;
  object: string;
  /**
   * A signed URL linking to the order preview PDF. The link remains valid for 15 minutes from the time of the API call.
   */
  url: string;
};

/** @internal */
export const PostcardsGetURLRequest$inboundSchema: z.ZodType<
  PostcardsGetURLRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type PostcardsGetURLRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostcardsGetURLRequest$outboundSchema: z.ZodType<
  PostcardsGetURLRequest$Outbound,
  z.ZodTypeDef,
  PostcardsGetURLRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardsGetURLRequest$ {
  /** @deprecated use `PostcardsGetURLRequest$inboundSchema` instead. */
  export const inboundSchema = PostcardsGetURLRequest$inboundSchema;
  /** @deprecated use `PostcardsGetURLRequest$outboundSchema` instead. */
  export const outboundSchema = PostcardsGetURLRequest$outboundSchema;
  /** @deprecated use `PostcardsGetURLRequest$Outbound` instead. */
  export type Outbound = PostcardsGetURLRequest$Outbound;
}

export function postcardsGetURLRequestToJSON(
  postcardsGetURLRequest: PostcardsGetURLRequest,
): string {
  return JSON.stringify(
    PostcardsGetURLRequest$outboundSchema.parse(postcardsGetURLRequest),
  );
}

export function postcardsGetURLRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostcardsGetURLRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardsGetURLRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardsGetURLRequest' from JSON`,
  );
}

/** @internal */
export const PostcardsGetURLResponseBody$inboundSchema: z.ZodType<
  PostcardsGetURLResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: z.string(),
  url: z.string(),
});

/** @internal */
export type PostcardsGetURLResponseBody$Outbound = {
  id: string;
  object: string;
  url: string;
};

/** @internal */
export const PostcardsGetURLResponseBody$outboundSchema: z.ZodType<
  PostcardsGetURLResponseBody$Outbound,
  z.ZodTypeDef,
  PostcardsGetURLResponseBody
> = z.object({
  id: z.string(),
  object: z.string(),
  url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardsGetURLResponseBody$ {
  /** @deprecated use `PostcardsGetURLResponseBody$inboundSchema` instead. */
  export const inboundSchema = PostcardsGetURLResponseBody$inboundSchema;
  /** @deprecated use `PostcardsGetURLResponseBody$outboundSchema` instead. */
  export const outboundSchema = PostcardsGetURLResponseBody$outboundSchema;
  /** @deprecated use `PostcardsGetURLResponseBody$Outbound` instead. */
  export type Outbound = PostcardsGetURLResponseBody$Outbound;
}

export function postcardsGetURLResponseBodyToJSON(
  postcardsGetURLResponseBody: PostcardsGetURLResponseBody,
): string {
  return JSON.stringify(
    PostcardsGetURLResponseBody$outboundSchema.parse(
      postcardsGetURLResponseBody,
    ),
  );
}

export function postcardsGetURLResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostcardsGetURLResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardsGetURLResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardsGetURLResponseBody' from JSON`,
  );
}
