/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostcardsListRequest = {
  skip?: number | undefined;
  limit?: number | undefined;
  /**
   * You can supply any string to help narrow down the list of resources. For example, if you pass `"New York"` (quoted), it will return resources that have that string present somewhere in their response. Alternatively, you can supply a structured search query. See the documentation on `StructuredSearchQuery` for more details.
   */
  search?: string | undefined;
};

/** @internal */
export const PostcardsListRequest$inboundSchema: z.ZodType<
  PostcardsListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  skip: z.number().int().default(0),
  limit: z.number().int().default(10),
  search: z.string().optional(),
});

/** @internal */
export type PostcardsListRequest$Outbound = {
  skip: number;
  limit: number;
  search?: string | undefined;
};

/** @internal */
export const PostcardsListRequest$outboundSchema: z.ZodType<
  PostcardsListRequest$Outbound,
  z.ZodTypeDef,
  PostcardsListRequest
> = z.object({
  skip: z.number().int().default(0),
  limit: z.number().int().default(10),
  search: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardsListRequest$ {
  /** @deprecated use `PostcardsListRequest$inboundSchema` instead. */
  export const inboundSchema = PostcardsListRequest$inboundSchema;
  /** @deprecated use `PostcardsListRequest$outboundSchema` instead. */
  export const outboundSchema = PostcardsListRequest$outboundSchema;
  /** @deprecated use `PostcardsListRequest$Outbound` instead. */
  export type Outbound = PostcardsListRequest$Outbound;
}

export function postcardsListRequestToJSON(
  postcardsListRequest: PostcardsListRequest,
): string {
  return JSON.stringify(
    PostcardsListRequest$outboundSchema.parse(postcardsListRequest),
  );
}

export function postcardsListRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostcardsListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardsListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardsListRequest' from JSON`,
  );
}
