/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SelfMailersListRequest = {
  skip?: number | undefined;
  limit?: number | undefined;
  /**
   * You can supply any string to help narrow down the list of resources. For example, if you pass `"New York"` (quoted), it will return resources that have that string present somewhere in their response. Alternatively, you can supply a structured search query. See the documentation on `StructuredSearchQuery` for more details.
   */
  search?: string | undefined;
};

/** @internal */
export const SelfMailersListRequest$inboundSchema: z.ZodType<
  SelfMailersListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  skip: z.number().int().default(0),
  limit: z.number().int().default(10),
  search: z.string().optional(),
});

/** @internal */
export type SelfMailersListRequest$Outbound = {
  skip: number;
  limit: number;
  search?: string | undefined;
};

/** @internal */
export const SelfMailersListRequest$outboundSchema: z.ZodType<
  SelfMailersListRequest$Outbound,
  z.ZodTypeDef,
  SelfMailersListRequest
> = z.object({
  skip: z.number().int().default(0),
  limit: z.number().int().default(10),
  search: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailersListRequest$ {
  /** @deprecated use `SelfMailersListRequest$inboundSchema` instead. */
  export const inboundSchema = SelfMailersListRequest$inboundSchema;
  /** @deprecated use `SelfMailersListRequest$outboundSchema` instead. */
  export const outboundSchema = SelfMailersListRequest$outboundSchema;
  /** @deprecated use `SelfMailersListRequest$Outbound` instead. */
  export type Outbound = SelfMailersListRequest$Outbound;
}

export function selfMailersListRequestToJSON(
  selfMailersListRequest: SelfMailersListRequest,
): string {
  return JSON.stringify(
    SelfMailersListRequest$outboundSchema.parse(selfMailersListRequest),
  );
}

export function selfMailersListRequestFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailersListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailersListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailersListRequest' from JSON`,
  );
}
