/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SelfMailersDeleteRequest = {
  /**
   * The ID of the self-mailer you want to cancel.
   */
  id: string;
};

/** @internal */
export const SelfMailersDeleteRequest$inboundSchema: z.ZodType<
  SelfMailersDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type SelfMailersDeleteRequest$Outbound = {
  id: string;
};

/** @internal */
export const SelfMailersDeleteRequest$outboundSchema: z.ZodType<
  SelfMailersDeleteRequest$Outbound,
  z.ZodTypeDef,
  SelfMailersDeleteRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailersDeleteRequest$ {
  /** @deprecated use `SelfMailersDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = SelfMailersDeleteRequest$inboundSchema;
  /** @deprecated use `SelfMailersDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = SelfMailersDeleteRequest$outboundSchema;
  /** @deprecated use `SelfMailersDeleteRequest$Outbound` instead. */
  export type Outbound = SelfMailersDeleteRequest$Outbound;
}

export function selfMailersDeleteRequestToJSON(
  selfMailersDeleteRequest: SelfMailersDeleteRequest,
): string {
  return JSON.stringify(
    SelfMailersDeleteRequest$outboundSchema.parse(selfMailersDeleteRequest),
  );
}

export function selfMailersDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailersDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailersDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailersDeleteRequest' from JSON`,
  );
}
