/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SelfMailersGetURLRequest = {
  /**
   * The ID of the self-mailer to retrieve the preview URL for.
   */
  id: string;
};

/**
 * the Self-Mailer Preview URL.
 */
export type SelfMailersGetURLResponseBody = {
  /**
   * A unique ID prefixed with self_mailer_
   */
  id: string;
  object: string;
  /**
   * A signed URL linking to the order preview PDF. The link remains valid for 15 minutes from the time of the API call.
   */
  url: string;
};

/** @internal */
export const SelfMailersGetURLRequest$inboundSchema: z.ZodType<
  SelfMailersGetURLRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type SelfMailersGetURLRequest$Outbound = {
  id: string;
};

/** @internal */
export const SelfMailersGetURLRequest$outboundSchema: z.ZodType<
  SelfMailersGetURLRequest$Outbound,
  z.ZodTypeDef,
  SelfMailersGetURLRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailersGetURLRequest$ {
  /** @deprecated use `SelfMailersGetURLRequest$inboundSchema` instead. */
  export const inboundSchema = SelfMailersGetURLRequest$inboundSchema;
  /** @deprecated use `SelfMailersGetURLRequest$outboundSchema` instead. */
  export const outboundSchema = SelfMailersGetURLRequest$outboundSchema;
  /** @deprecated use `SelfMailersGetURLRequest$Outbound` instead. */
  export type Outbound = SelfMailersGetURLRequest$Outbound;
}

export function selfMailersGetURLRequestToJSON(
  selfMailersGetURLRequest: SelfMailersGetURLRequest,
): string {
  return JSON.stringify(
    SelfMailersGetURLRequest$outboundSchema.parse(selfMailersGetURLRequest),
  );
}

export function selfMailersGetURLRequestFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailersGetURLRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailersGetURLRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailersGetURLRequest' from JSON`,
  );
}

/** @internal */
export const SelfMailersGetURLResponseBody$inboundSchema: z.ZodType<
  SelfMailersGetURLResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: z.string(),
  url: z.string(),
});

/** @internal */
export type SelfMailersGetURLResponseBody$Outbound = {
  id: string;
  object: string;
  url: string;
};

/** @internal */
export const SelfMailersGetURLResponseBody$outboundSchema: z.ZodType<
  SelfMailersGetURLResponseBody$Outbound,
  z.ZodTypeDef,
  SelfMailersGetURLResponseBody
> = z.object({
  id: z.string(),
  object: z.string(),
  url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailersGetURLResponseBody$ {
  /** @deprecated use `SelfMailersGetURLResponseBody$inboundSchema` instead. */
  export const inboundSchema = SelfMailersGetURLResponseBody$inboundSchema;
  /** @deprecated use `SelfMailersGetURLResponseBody$outboundSchema` instead. */
  export const outboundSchema = SelfMailersGetURLResponseBody$outboundSchema;
  /** @deprecated use `SelfMailersGetURLResponseBody$Outbound` instead. */
  export type Outbound = SelfMailersGetURLResponseBody$Outbound;
}

export function selfMailersGetURLResponseBodyToJSON(
  selfMailersGetURLResponseBody: SelfMailersGetURLResponseBody,
): string {
  return JSON.stringify(
    SelfMailersGetURLResponseBody$outboundSchema.parse(
      selfMailersGetURLResponseBody,
    ),
  );
}

export function selfMailersGetURLResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailersGetURLResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailersGetURLResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailersGetURLResponseBody' from JSON`,
  );
}
