/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TemplatesGetRequest = {
  /**
   * The ID of the template to retrieve.
   */
  id: string;
};

/** @internal */
export const TemplatesGetRequest$inboundSchema: z.ZodType<
  TemplatesGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type TemplatesGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const TemplatesGetRequest$outboundSchema: z.ZodType<
  TemplatesGetRequest$Outbound,
  z.ZodTypeDef,
  TemplatesGetRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TemplatesGetRequest$ {
  /** @deprecated use `TemplatesGetRequest$inboundSchema` instead. */
  export const inboundSchema = TemplatesGetRequest$inboundSchema;
  /** @deprecated use `TemplatesGetRequest$outboundSchema` instead. */
  export const outboundSchema = TemplatesGetRequest$outboundSchema;
  /** @deprecated use `TemplatesGetRequest$Outbound` instead. */
  export type Outbound = TemplatesGetRequest$Outbound;
}

export function templatesGetRequestToJSON(
  templatesGetRequest: TemplatesGetRequest,
): string {
  return JSON.stringify(
    TemplatesGetRequest$outboundSchema.parse(templatesGetRequest),
  );
}

export function templatesGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<TemplatesGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TemplatesGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TemplatesGetRequest' from JSON`,
  );
}
