/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Enum representing the placement of the attached PDF.
 */
export const AttachedPDFPlacement = {
  BeforeTemplate: "before_template",
  AfterTemplate: "after_template",
} as const;
/**
 * Enum representing the placement of the attached PDF.
 */
export type AttachedPDFPlacement = ClosedEnum<typeof AttachedPDFPlacement>;

/** @internal */
export const AttachedPDFPlacement$inboundSchema: z.ZodNativeEnum<
  typeof AttachedPDFPlacement
> = z.nativeEnum(AttachedPDFPlacement);

/** @internal */
export const AttachedPDFPlacement$outboundSchema: z.ZodNativeEnum<
  typeof AttachedPDFPlacement
> = AttachedPDFPlacement$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AttachedPDFPlacement$ {
  /** @deprecated use `AttachedPDFPlacement$inboundSchema` instead. */
  export const inboundSchema = AttachedPDFPlacement$inboundSchema;
  /** @deprecated use `AttachedPDFPlacement$outboundSchema` instead. */
  export const outboundSchema = AttachedPDFPlacement$outboundSchema;
}
