/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BankAccountCreateSignatureImageFile,
  BankAccountCreateSignatureImageFile$inboundSchema,
  BankAccountCreateSignatureImageFile$Outbound,
  BankAccountCreateSignatureImageFile$outboundSchema,
} from "./bankaccountcreatesignatureimagefile.js";
import {
  BankAccountCreateSignatureImageURL,
  BankAccountCreateSignatureImageURL$inboundSchema,
  BankAccountCreateSignatureImageURL$Outbound,
  BankAccountCreateSignatureImageURL$outboundSchema,
} from "./bankaccountcreatesignatureimageurl.js";
import {
  BankAccountCreateSignatureText,
  BankAccountCreateSignatureText$inboundSchema,
  BankAccountCreateSignatureText$Outbound,
  BankAccountCreateSignatureText$outboundSchema,
} from "./bankaccountcreatesignaturetext.js";

export type BankAccountCreate =
  | BankAccountCreateSignatureText
  | BankAccountCreateSignatureImageURL
  | BankAccountCreateSignatureImageFile;

/** @internal */
export const BankAccountCreate$inboundSchema: z.ZodType<
  BankAccountCreate,
  z.ZodTypeDef,
  unknown
> = z.union([
  BankAccountCreateSignatureText$inboundSchema,
  BankAccountCreateSignatureImageURL$inboundSchema,
  BankAccountCreateSignatureImageFile$inboundSchema,
]);

/** @internal */
export type BankAccountCreate$Outbound =
  | BankAccountCreateSignatureText$Outbound
  | BankAccountCreateSignatureImageURL$Outbound
  | BankAccountCreateSignatureImageFile$Outbound;

/** @internal */
export const BankAccountCreate$outboundSchema: z.ZodType<
  BankAccountCreate$Outbound,
  z.ZodTypeDef,
  BankAccountCreate
> = z.union([
  BankAccountCreateSignatureText$outboundSchema,
  BankAccountCreateSignatureImageURL$outboundSchema,
  BankAccountCreateSignatureImageFile$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BankAccountCreate$ {
  /** @deprecated use `BankAccountCreate$inboundSchema` instead. */
  export const inboundSchema = BankAccountCreate$inboundSchema;
  /** @deprecated use `BankAccountCreate$outboundSchema` instead. */
  export const outboundSchema = BankAccountCreate$outboundSchema;
  /** @deprecated use `BankAccountCreate$Outbound` instead. */
  export type Outbound = BankAccountCreate$Outbound;
}

export function bankAccountCreateToJSON(
  bankAccountCreate: BankAccountCreate,
): string {
  return JSON.stringify(
    BankAccountCreate$outboundSchema.parse(bankAccountCreate),
  );
}

export function bankAccountCreateFromJSON(
  jsonString: string,
): SafeParseResult<BankAccountCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BankAccountCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BankAccountCreate' from JSON`,
  );
}
