/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BankAccountCountryCode,
  BankAccountCountryCode$inboundSchema,
  BankAccountCountryCode$outboundSchema,
} from "./bankaccountcountrycode.js";

export type BankAccountCreateSignatureImageURL = {
  /**
   * The name of the bank.
   */
  bankName: string;
  /**
   * The primary address line of the bank.
   */
  bankPrimaryLine?: string | undefined;
  /**
   * The secondary address line of the bank.
   */
  bankSecondaryLine?: string | undefined;
  /**
   * The country code of the bank.
   */
  bankCountryCode: BankAccountCountryCode;
  /**
   * The account number of the bank account.
   */
  accountNumber: string;
  /**
   * The routing number of the bank account (for US).
   */
  routingNumber?: string | undefined;
  /**
   * The transit number of the bank account (for CA).
   */
  transitNumber?: string | undefined;
  /**
   * The route number of the bank account (for CA).
   */
  routeNumber?: string | undefined;
  /**
   * An optional string describing this resource. Will be visible in the API and the dashboard.
   */
  description?: string | undefined;
  /**
   * See the section on Metadata.
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * Link to signature image which PostGrid will download and apply to cheques created with this bank account.
   */
  signatureImage: string;
};

/** @internal */
export const BankAccountCreateSignatureImageURL$inboundSchema: z.ZodType<
  BankAccountCreateSignatureImageURL,
  z.ZodTypeDef,
  unknown
> = z.object({
  bankName: z.string(),
  bankPrimaryLine: z.string().optional(),
  bankSecondaryLine: z.string().optional(),
  bankCountryCode: BankAccountCountryCode$inboundSchema,
  accountNumber: z.string(),
  routingNumber: z.string().optional(),
  transitNumber: z.string().optional(),
  routeNumber: z.string().optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  signatureImage: z.string(),
});

/** @internal */
export type BankAccountCreateSignatureImageURL$Outbound = {
  bankName: string;
  bankPrimaryLine?: string | undefined;
  bankSecondaryLine?: string | undefined;
  bankCountryCode: string;
  accountNumber: string;
  routingNumber?: string | undefined;
  transitNumber?: string | undefined;
  routeNumber?: string | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  signatureImage: string;
};

/** @internal */
export const BankAccountCreateSignatureImageURL$outboundSchema: z.ZodType<
  BankAccountCreateSignatureImageURL$Outbound,
  z.ZodTypeDef,
  BankAccountCreateSignatureImageURL
> = z.object({
  bankName: z.string(),
  bankPrimaryLine: z.string().optional(),
  bankSecondaryLine: z.string().optional(),
  bankCountryCode: BankAccountCountryCode$outboundSchema,
  accountNumber: z.string(),
  routingNumber: z.string().optional(),
  transitNumber: z.string().optional(),
  routeNumber: z.string().optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  signatureImage: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BankAccountCreateSignatureImageURL$ {
  /** @deprecated use `BankAccountCreateSignatureImageURL$inboundSchema` instead. */
  export const inboundSchema = BankAccountCreateSignatureImageURL$inboundSchema;
  /** @deprecated use `BankAccountCreateSignatureImageURL$outboundSchema` instead. */
  export const outboundSchema =
    BankAccountCreateSignatureImageURL$outboundSchema;
  /** @deprecated use `BankAccountCreateSignatureImageURL$Outbound` instead. */
  export type Outbound = BankAccountCreateSignatureImageURL$Outbound;
}

export function bankAccountCreateSignatureImageURLToJSON(
  bankAccountCreateSignatureImageURL: BankAccountCreateSignatureImageURL,
): string {
  return JSON.stringify(
    BankAccountCreateSignatureImageURL$outboundSchema.parse(
      bankAccountCreateSignatureImageURL,
    ),
  );
}

export function bankAccountCreateSignatureImageURLFromJSON(
  jsonString: string,
): SafeParseResult<BankAccountCreateSignatureImageURL, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      BankAccountCreateSignatureImageURL$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BankAccountCreateSignatureImageURL' from JSON`,
  );
}
