/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Countries typically have different bank account formats and standards. These are the countries
 *
 * @remarks
 * which PostGrid's bank accounts API supports.
 */
export const BankAccountCountryCode = {
  Ca: "CA",
  Us: "US",
} as const;
/**
 * Countries typically have different bank account formats and standards. These are the countries
 *
 * @remarks
 * which PostGrid's bank accounts API supports.
 */
export type BankAccountCountryCode = ClosedEnum<typeof BankAccountCountryCode>;

/** @internal */
export const BankAccountCountryCode$inboundSchema: z.ZodNativeEnum<
  typeof BankAccountCountryCode
> = z.nativeEnum(BankAccountCountryCode);

/** @internal */
export const BankAccountCountryCode$outboundSchema: z.ZodNativeEnum<
  typeof BankAccountCountryCode
> = BankAccountCountryCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BankAccountCountryCode$ {
  /** @deprecated use `BankAccountCountryCode$inboundSchema` instead. */
  export const inboundSchema = BankAccountCountryCode$inboundSchema;
  /** @deprecated use `BankAccountCountryCode$outboundSchema` instead. */
  export const outboundSchema = BankAccountCountryCode$outboundSchema;
}
