/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Enum representing the supported letter sizes.
 */
export const LetterSize = {
  UsLetter: "us_letter",
  A4: "a4",
} as const;
/**
 * Enum representing the supported letter sizes.
 */
export type LetterSize = ClosedEnum<typeof LetterSize>;

/** @internal */
export const LetterSize$inboundSchema: z.ZodNativeEnum<typeof LetterSize> = z
  .nativeEnum(LetterSize);

/** @internal */
export const LetterSize$outboundSchema: z.ZodNativeEnum<typeof LetterSize> =
  LetterSize$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LetterSize$ {
  /** @deprecated use `LetterSize$inboundSchema` instead. */
  export const inboundSchema = LetterSize$inboundSchema;
  /** @deprecated use `LetterSize$outboundSchema` instead. */
  export const outboundSchema = LetterSize$outboundSchema;
}
