/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AddressPlacement,
  AddressPlacement$inboundSchema,
  AddressPlacement$outboundSchema,
} from "./addressplacement.js";
import {
  AttachedPDF,
  AttachedPDF$inboundSchema,
  AttachedPDF$Outbound,
  AttachedPDF$outboundSchema,
} from "./attachedpdf.js";
import {
  Cancellation,
  Cancellation$inboundSchema,
  Cancellation$Outbound,
  Cancellation$outboundSchema,
} from "./cancellation.js";
import {
  Contact,
  Contact$inboundSchema,
  Contact$Outbound,
  Contact$outboundSchema,
} from "./contact.js";
import {
  LetterSize,
  LetterSize$inboundSchema,
  LetterSize$outboundSchema,
} from "./lettersize.js";
import {
  OrderIMBStatus,
  OrderIMBStatus$inboundSchema,
  OrderIMBStatus$outboundSchema,
} from "./orderimbstatus.js";
import {
  OrderMailingClass,
  OrderMailingClass$inboundSchema,
  OrderMailingClass$outboundSchema,
} from "./ordermailingclass.js";
import {
  OrderStatus,
  OrderStatus$inboundSchema,
  OrderStatus$outboundSchema,
} from "./orderstatus.js";
import {
  PlasticCard,
  PlasticCard$inboundSchema,
  PlasticCard$Outbound,
  PlasticCard$outboundSchema,
} from "./plasticcard.js";

/**
 * Always `letter`.
 */
export const LetterObject = {
  Letter: "letter",
} as const;
/**
 * Always `letter`.
 */
export type LetterObject = ClosedEnum<typeof LetterObject>;

export type Letter = {
  /**
   * See `OrderStatus` for more details on the status of this order.
   */
  status: OrderStatus;
  /**
   * These will be merged with the variables in the template or HTML you create this order with. The keys in this object should match the variable names in the template _exactly_ as they are case-sensitive. Note that these _do not_ apply to PDFs uploaded with the order.
   */
  mergeVariables?: { [k: string]: any } | undefined;
  /**
   * The tracking number of this order. Populated after an express/certified order has been processed for delivery.
   */
  trackingNumber?: string | undefined;
  /**
   * The Intelligent Mail Barcode (IMB) status of this order. Only populated for US-printed and US-destined orders. This is the most detailed way to track non-express/certified orders.
   */
  imbStatus?: OrderIMBStatus | undefined;
  /**
   * The most recent ZIP code of the USPS facility that the order has been processed through. Only populated when an `imbStatus` is present.
   */
  imbZIPCode?: string | undefined;
  /**
   * The last date that the IMB status was updated. See `imbStatus` for more details.
   */
  imbDate?: Date | undefined;
  /**
   * The cancellation details of this order. Populated if the order has been cancelled.
   */
  cancellation?: Cancellation | undefined;
  /**
   * PostGrid renders a PDF preview for all orders. This should be inspected to ensure that the order is correct before it is sent out because it shows what will be printed and mailed to the recipient. Once the PDF preview is generated, this field will be returned by all `GET` endpoints which produce this order.
   *
   * @remarks
   *
   * This URL is a signed link to the PDF preview. It will expire after a short period of time. If you need to access this URL after it has expired, you can regenerate it by calling the `GET` endpoint again.
   */
  url?: string | undefined;
  /**
   * A unique ID prefixed with letter_
   */
  id: string;
  /**
   * An optional string describing this resource. Will be visible in the API and the dashboard.
   */
  description?: string | undefined;
  /**
   * See the section on Metadata.
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * `true` if this is a live mode resource else `false`.
   */
  live: boolean;
  /**
   * The UTC time at which this resource was created.
   */
  createdAt: Date;
  /**
   * The UTC time at which this resource was last updated.
   */
  updatedAt: Date;
  /**
   * This order will transition from `ready` to `printing` on the day after this date. For example, if this is a date on Tuesday, the order will transition to `printing` on Wednesday at midnight eastern time.
   */
  sendDate: Date;
  /**
   * The mailing class of this order. This determines the speed and cost of delivery. See `OrderMailingClass` for more details.
   */
  mailingClass: OrderMailingClass;
  /**
   * The recipient of this order. This will be provided even if you delete the underlying contact.
   */
  to: Contact;
  /**
   * Always `letter`.
   */
  object: LetterObject;
  /**
   * If specified, indicates which letter page is perforated. Currently, only the first page can be perforated.
   */
  perforatedPage?: number | undefined;
  /**
   * The return envelope (ID) sent out with the letter, if any.
   */
  returnEnvelope?: string | undefined;
  /**
   * You can attach a PDF to the content you supply for this letter. This is useful if you have some stati
   */
  attachedPDF?: AttachedPDF | undefined;
  /**
   * The plastic card sent out with the letter, if any.
   */
  plasticCard?: PlasticCard | undefined;
  /**
   * The ID of the PDF workflow run that created the letter, if any.
   */
  pdfWorkflowRun?: string | undefined;
  /**
   * The contact information of the sender.
   */
  from: Contact;
  /**
   * Indicates if the letter is double-sided.
   */
  doubleSided: boolean;
  /**
   * Indicates if the letter is in color.
   */
  color: boolean;
  /**
   * The size of the letter.
   */
  size: LetterSize;
  /**
   * The placement of the address on the letter.
   */
  addressPlacement: AddressPlacement;
  /**
   * The envelope (ID) for the letter or the default `standard` envelope.
   */
  envelope: string;
  /**
   * The HTML content for the letter. You can supply _either_ this or `template` but not both.
   */
  html?: string | undefined;
  /**
   * The template ID used for the letter. You can supply _either_ this or `html` but not both.
   */
  template?: string | undefined;
  /**
   * If a PDF was uploaded for the letter, this will contain the signed link to the uploaded PDF.
   */
  uploadedPDF?: string | undefined;
};

/** @internal */
export const LetterObject$inboundSchema: z.ZodNativeEnum<typeof LetterObject> =
  z.nativeEnum(LetterObject);

/** @internal */
export const LetterObject$outboundSchema: z.ZodNativeEnum<typeof LetterObject> =
  LetterObject$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LetterObject$ {
  /** @deprecated use `LetterObject$inboundSchema` instead. */
  export const inboundSchema = LetterObject$inboundSchema;
  /** @deprecated use `LetterObject$outboundSchema` instead. */
  export const outboundSchema = LetterObject$outboundSchema;
}

/** @internal */
export const Letter$inboundSchema: z.ZodType<Letter, z.ZodTypeDef, unknown> = z
  .object({
    status: OrderStatus$inboundSchema,
    mergeVariables: z.record(z.any()).optional(),
    trackingNumber: z.string().optional(),
    imbStatus: OrderIMBStatus$inboundSchema.optional(),
    imbZIPCode: z.string().optional(),
    imbDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    cancellation: Cancellation$inboundSchema.optional(),
    url: z.string().optional(),
    id: z.string(),
    description: z.string().optional(),
    metadata: z.record(z.any()).optional(),
    live: z.boolean(),
    createdAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    updatedAt: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    sendDate: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    mailingClass: OrderMailingClass$inboundSchema,
    to: Contact$inboundSchema,
    object: LetterObject$inboundSchema,
    perforatedPage: z.number().optional(),
    returnEnvelope: z.string().optional(),
    attachedPDF: AttachedPDF$inboundSchema.optional(),
    plasticCard: PlasticCard$inboundSchema.optional(),
    pdfWorkflowRun: z.string().optional(),
    from: Contact$inboundSchema,
    doubleSided: z.boolean(),
    color: z.boolean(),
    size: LetterSize$inboundSchema,
    addressPlacement: AddressPlacement$inboundSchema,
    envelope: z.string(),
    html: z.string().optional(),
    template: z.string().optional(),
    uploadedPDF: z.string().optional(),
  });

/** @internal */
export type Letter$Outbound = {
  status: string;
  mergeVariables?: { [k: string]: any } | undefined;
  trackingNumber?: string | undefined;
  imbStatus?: string | undefined;
  imbZIPCode?: string | undefined;
  imbDate?: string | undefined;
  cancellation?: Cancellation$Outbound | undefined;
  url?: string | undefined;
  id: string;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  live: boolean;
  createdAt: string;
  updatedAt: string;
  sendDate: string;
  mailingClass: string;
  to: Contact$Outbound;
  object: string;
  perforatedPage?: number | undefined;
  returnEnvelope?: string | undefined;
  attachedPDF?: AttachedPDF$Outbound | undefined;
  plasticCard?: PlasticCard$Outbound | undefined;
  pdfWorkflowRun?: string | undefined;
  from: Contact$Outbound;
  doubleSided: boolean;
  color: boolean;
  size: string;
  addressPlacement: string;
  envelope: string;
  html?: string | undefined;
  template?: string | undefined;
  uploadedPDF?: string | undefined;
};

/** @internal */
export const Letter$outboundSchema: z.ZodType<
  Letter$Outbound,
  z.ZodTypeDef,
  Letter
> = z.object({
  status: OrderStatus$outboundSchema,
  mergeVariables: z.record(z.any()).optional(),
  trackingNumber: z.string().optional(),
  imbStatus: OrderIMBStatus$outboundSchema.optional(),
  imbZIPCode: z.string().optional(),
  imbDate: z.date().transform(v => v.toISOString()).optional(),
  cancellation: Cancellation$outboundSchema.optional(),
  url: z.string().optional(),
  id: z.string(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  live: z.boolean(),
  createdAt: z.date().transform(v => v.toISOString()),
  updatedAt: z.date().transform(v => v.toISOString()),
  sendDate: z.date().transform(v => v.toISOString()),
  mailingClass: OrderMailingClass$outboundSchema,
  to: Contact$outboundSchema,
  object: LetterObject$outboundSchema,
  perforatedPage: z.number().optional(),
  returnEnvelope: z.string().optional(),
  attachedPDF: AttachedPDF$outboundSchema.optional(),
  plasticCard: PlasticCard$outboundSchema.optional(),
  pdfWorkflowRun: z.string().optional(),
  from: Contact$outboundSchema,
  doubleSided: z.boolean(),
  color: z.boolean(),
  size: LetterSize$outboundSchema,
  addressPlacement: AddressPlacement$outboundSchema,
  envelope: z.string(),
  html: z.string().optional(),
  template: z.string().optional(),
  uploadedPDF: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Letter$ {
  /** @deprecated use `Letter$inboundSchema` instead. */
  export const inboundSchema = Letter$inboundSchema;
  /** @deprecated use `Letter$outboundSchema` instead. */
  export const outboundSchema = Letter$outboundSchema;
  /** @deprecated use `Letter$Outbound` instead. */
  export type Outbound = Letter$Outbound;
}

export function letterToJSON(letter: Letter): string {
  return JSON.stringify(Letter$outboundSchema.parse(letter));
}

export function letterFromJSON(
  jsonString: string,
): SafeParseResult<Letter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Letter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Letter' from JSON`,
  );
}
