/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LetterCreateWithTemplate = {
  /**
   * The template ID for the letter. You can supply _either_ this or `html` but not both.
   */
  template: string;
};

/** @internal */
export const LetterCreateWithTemplate$inboundSchema: z.ZodType<
  LetterCreateWithTemplate,
  z.ZodTypeDef,
  unknown
> = z.object({
  template: z.string(),
});

/** @internal */
export type LetterCreateWithTemplate$Outbound = {
  template: string;
};

/** @internal */
export const LetterCreateWithTemplate$outboundSchema: z.ZodType<
  LetterCreateWithTemplate$Outbound,
  z.ZodTypeDef,
  LetterCreateWithTemplate
> = z.object({
  template: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LetterCreateWithTemplate$ {
  /** @deprecated use `LetterCreateWithTemplate$inboundSchema` instead. */
  export const inboundSchema = LetterCreateWithTemplate$inboundSchema;
  /** @deprecated use `LetterCreateWithTemplate$outboundSchema` instead. */
  export const outboundSchema = LetterCreateWithTemplate$outboundSchema;
  /** @deprecated use `LetterCreateWithTemplate$Outbound` instead. */
  export type Outbound = LetterCreateWithTemplate$Outbound;
}

export function letterCreateWithTemplateToJSON(
  letterCreateWithTemplate: LetterCreateWithTemplate,
): string {
  return JSON.stringify(
    LetterCreateWithTemplate$outboundSchema.parse(letterCreateWithTemplate),
  );
}

export function letterCreateWithTemplateFromJSON(
  jsonString: string,
): SafeParseResult<LetterCreateWithTemplate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LetterCreateWithTemplate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LetterCreateWithTemplate' from JSON`,
  );
}
