/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const OrderIMBStatus = {
  EnteredMailStream: "entered_mail_stream",
  OutForDelivery: "out_for_delivery",
  ReturnedToSender: "returned_to_sender",
} as const;
export type OrderIMBStatus = ClosedEnum<typeof OrderIMBStatus>;

/** @internal */
export const OrderIMBStatus$inboundSchema: z.ZodNativeEnum<
  typeof OrderIMBStatus
> = z.nativeEnum(OrderIMBStatus);

/** @internal */
export const OrderIMBStatus$outboundSchema: z.ZodNativeEnum<
  typeof OrderIMBStatus
> = OrderIMBStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderIMBStatus$ {
  /** @deprecated use `OrderIMBStatus$inboundSchema` instead. */
  export const inboundSchema = OrderIMBStatus$inboundSchema;
  /** @deprecated use `OrderIMBStatus$outboundSchema` instead. */
  export const outboundSchema = OrderIMBStatus$outboundSchema;
}
