/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const OrderMailingClass = {
  FirstClass: "first_class",
  StandardClass: "standard_class",
  Express: "express",
  Certified: "certified",
  CertifiedReturnReceipt: "certified_return_receipt",
  Registered: "registered",
  UspsFirstClass: "usps_first_class",
  UspsStandardClass: "usps_standard_class",
  UspsEddm: "usps_eddm",
  UspsExpress2Day: "usps_express_2_day",
  UspsExpress3Day: "usps_express_3_day",
  UspsFirstClassCertified: "usps_first_class_certified",
  UspsFirstClassCertifiedReturnReceipt:
    "usps_first_class_certified_return_receipt",
  UspsFirstClassRegistered: "usps_first_class_registered",
  UspsExpress3DaySignatureConfirmation:
    "usps_express_3_day_signature_confirmation",
  UspsExpress3DayCertified: "usps_express_3_day_certified",
  UspsExpress3DayCertifiedReturnReceipt:
    "usps_express_3_day_certified_return_receipt",
  CaPostLettermail: "ca_post_lettermail",
  CaPostPersonalized: "ca_post_personalized",
  CaPostNeighbourhoodMail: "ca_post_neighbourhood_mail",
  UpsExpressOvernight: "ups_express_overnight",
  UpsExpress2Day: "ups_express_2_day",
  UpsExpress3Day: "ups_express_3_day",
  RoyalMailFirstClass: "royal_mail_first_class",
  RoyalMailSecondClass: "royal_mail_second_class",
  AuPostSecondClass: "au_post_second_class",
} as const;
export type OrderMailingClass = ClosedEnum<typeof OrderMailingClass>;

/** @internal */
export const OrderMailingClass$inboundSchema: z.ZodNativeEnum<
  typeof OrderMailingClass
> = z.nativeEnum(OrderMailingClass);

/** @internal */
export const OrderMailingClass$outboundSchema: z.ZodNativeEnum<
  typeof OrderMailingClass
> = OrderMailingClass$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrderMailingClass$ {
  /** @deprecated use `OrderMailingClass$inboundSchema` instead. */
  export const inboundSchema = OrderMailingClass$inboundSchema;
  /** @deprecated use `OrderMailingClass$outboundSchema` instead. */
  export const outboundSchema = OrderMailingClass$outboundSchema;
}
