/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Enum representing the size of the plastic card.
 */
export const PlasticCardSize = {
  Standard: "standard",
} as const;
/**
 * Enum representing the size of the plastic card.
 */
export type PlasticCardSize = ClosedEnum<typeof PlasticCardSize>;

/** @internal */
export const PlasticCardSize$inboundSchema: z.ZodNativeEnum<
  typeof PlasticCardSize
> = z.nativeEnum(PlasticCardSize);

/** @internal */
export const PlasticCardSize$outboundSchema: z.ZodNativeEnum<
  typeof PlasticCardSize
> = PlasticCardSize$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlasticCardSize$ {
  /** @deprecated use `PlasticCardSize$inboundSchema` instead. */
  export const inboundSchema = PlasticCardSize$inboundSchema;
  /** @deprecated use `PlasticCardSize$outboundSchema` instead. */
  export const outboundSchema = PlasticCardSize$outboundSchema;
}
