/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PostcardCreateWithHTML,
  PostcardCreateWithHTML$inboundSchema,
  PostcardCreateWithHTML$Outbound,
  PostcardCreateWithHTML$outboundSchema,
} from "./postcardcreatewithhtml.js";
import {
  PostcardCreateWithPDFFile,
  PostcardCreateWithPDFFile$inboundSchema,
  PostcardCreateWithPDFFile$Outbound,
  PostcardCreateWithPDFFile$outboundSchema,
} from "./postcardcreatewithpdffile.js";
import {
  PostcardCreateWithPDFURL,
  PostcardCreateWithPDFURL$inboundSchema,
  PostcardCreateWithPDFURL$Outbound,
  PostcardCreateWithPDFURL$outboundSchema,
} from "./postcardcreatewithpdfurl.js";
import {
  PostcardCreateWithTemplate,
  PostcardCreateWithTemplate$inboundSchema,
  PostcardCreateWithTemplate$Outbound,
  PostcardCreateWithTemplate$outboundSchema,
} from "./postcardcreatewithtemplate.js";

export type PostcardCreate =
  | PostcardCreateWithTemplate
  | PostcardCreateWithPDFURL
  | PostcardCreateWithPDFFile
  | PostcardCreateWithHTML;

/** @internal */
export const PostcardCreate$inboundSchema: z.ZodType<
  PostcardCreate,
  z.ZodTypeDef,
  unknown
> = z.union([
  PostcardCreateWithTemplate$inboundSchema,
  PostcardCreateWithPDFURL$inboundSchema,
  PostcardCreateWithPDFFile$inboundSchema,
  PostcardCreateWithHTML$inboundSchema,
]);

/** @internal */
export type PostcardCreate$Outbound =
  | PostcardCreateWithTemplate$Outbound
  | PostcardCreateWithPDFURL$Outbound
  | PostcardCreateWithPDFFile$Outbound
  | PostcardCreateWithHTML$Outbound;

/** @internal */
export const PostcardCreate$outboundSchema: z.ZodType<
  PostcardCreate$Outbound,
  z.ZodTypeDef,
  PostcardCreate
> = z.union([
  PostcardCreateWithTemplate$outboundSchema,
  PostcardCreateWithPDFURL$outboundSchema,
  PostcardCreateWithPDFFile$outboundSchema,
  PostcardCreateWithHTML$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardCreate$ {
  /** @deprecated use `PostcardCreate$inboundSchema` instead. */
  export const inboundSchema = PostcardCreate$inboundSchema;
  /** @deprecated use `PostcardCreate$outboundSchema` instead. */
  export const outboundSchema = PostcardCreate$outboundSchema;
  /** @deprecated use `PostcardCreate$Outbound` instead. */
  export type Outbound = PostcardCreate$Outbound;
}

export function postcardCreateToJSON(postcardCreate: PostcardCreate): string {
  return JSON.stringify(PostcardCreate$outboundSchema.parse(postcardCreate));
}

export function postcardCreateFromJSON(
  jsonString: string,
): SafeParseResult<PostcardCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardCreate' from JSON`,
  );
}
