/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ContactCreate,
  ContactCreate$inboundSchema,
  ContactCreate$Outbound,
  ContactCreate$outboundSchema,
} from "./contactcreate.js";
import {
  OrderMailingClass,
  OrderMailingClass$inboundSchema,
  OrderMailingClass$outboundSchema,
} from "./ordermailingclass.js";
import {
  PostcardSize,
  PostcardSize$inboundSchema,
  PostcardSize$outboundSchema,
} from "./postcardsize.js";

/**
 * The recipient of this order. You can either supply the contact information inline here or provide a contact ID. PostGrid will automatically deduplicate contacts regardless of whether you provide the information inline here or call the contact creation endpoint.
 */
export type PostcardCreateWithPDFFileTo = ContactCreate | string;

/**
 * The contact information of the sender. You can pass contact information inline here just like you can for the `to`. Unlike other order types, the sender address is optional for postcards.
 */
export type PostcardCreateWithPDFFileFrom = ContactCreate | string;

export type PostcardCreateWithPDFFile = {
  /**
   * These will be merged with the variables in the template or HTML you create this order with. The keys in this object should match the variable names in the template _exactly_ as they are case-sensitive. Note that these _do not_ apply to PDFs uploaded with the order.
   */
  mergeVariables?: { [k: string]: any } | undefined;
  /**
   * An optional string describing this resource. Will be visible in the API and the dashboard.
   */
  description?: string | undefined;
  /**
   * See the section on Metadata.
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * This order will transition from `ready` to `printing` on the day after this date. You can use this parameter to schedule orders for a future date.
   */
  sendDate?: Date | undefined;
  /**
   * The mailing class of this order. If not provided, automatically set to `first_class`.
   */
  mailingClass?: OrderMailingClass | undefined;
  /**
   * The recipient of this order. You can either supply the contact information inline here or provide a contact ID. PostGrid will automatically deduplicate contacts regardless of whether you provide the information inline here or call the contact creation endpoint.
   */
  to: ContactCreate | string;
  /**
   * The size of the postcard.
   */
  size: PostcardSize;
  /**
   * The contact information of the sender. You can pass contact information inline here just like you can for the `to`. Unlike other order types, the sender address is optional for postcards.
   */
  from?: ContactCreate | string | undefined;
  /**
   * A 2 page PDF file. The first page is the front of the postcard and the second page is the back (where the address will be stamped on).
   */
  pdf: string;
};

/** @internal */
export const PostcardCreateWithPDFFileTo$inboundSchema: z.ZodType<
  PostcardCreateWithPDFFileTo,
  z.ZodTypeDef,
  unknown
> = z.union([ContactCreate$inboundSchema, z.string()]);

/** @internal */
export type PostcardCreateWithPDFFileTo$Outbound =
  | ContactCreate$Outbound
  | string;

/** @internal */
export const PostcardCreateWithPDFFileTo$outboundSchema: z.ZodType<
  PostcardCreateWithPDFFileTo$Outbound,
  z.ZodTypeDef,
  PostcardCreateWithPDFFileTo
> = z.union([ContactCreate$outboundSchema, z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardCreateWithPDFFileTo$ {
  /** @deprecated use `PostcardCreateWithPDFFileTo$inboundSchema` instead. */
  export const inboundSchema = PostcardCreateWithPDFFileTo$inboundSchema;
  /** @deprecated use `PostcardCreateWithPDFFileTo$outboundSchema` instead. */
  export const outboundSchema = PostcardCreateWithPDFFileTo$outboundSchema;
  /** @deprecated use `PostcardCreateWithPDFFileTo$Outbound` instead. */
  export type Outbound = PostcardCreateWithPDFFileTo$Outbound;
}

export function postcardCreateWithPDFFileToToJSON(
  postcardCreateWithPDFFileTo: PostcardCreateWithPDFFileTo,
): string {
  return JSON.stringify(
    PostcardCreateWithPDFFileTo$outboundSchema.parse(
      postcardCreateWithPDFFileTo,
    ),
  );
}

export function postcardCreateWithPDFFileToFromJSON(
  jsonString: string,
): SafeParseResult<PostcardCreateWithPDFFileTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardCreateWithPDFFileTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardCreateWithPDFFileTo' from JSON`,
  );
}

/** @internal */
export const PostcardCreateWithPDFFileFrom$inboundSchema: z.ZodType<
  PostcardCreateWithPDFFileFrom,
  z.ZodTypeDef,
  unknown
> = z.union([ContactCreate$inboundSchema, z.string()]);

/** @internal */
export type PostcardCreateWithPDFFileFrom$Outbound =
  | ContactCreate$Outbound
  | string;

/** @internal */
export const PostcardCreateWithPDFFileFrom$outboundSchema: z.ZodType<
  PostcardCreateWithPDFFileFrom$Outbound,
  z.ZodTypeDef,
  PostcardCreateWithPDFFileFrom
> = z.union([ContactCreate$outboundSchema, z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardCreateWithPDFFileFrom$ {
  /** @deprecated use `PostcardCreateWithPDFFileFrom$inboundSchema` instead. */
  export const inboundSchema = PostcardCreateWithPDFFileFrom$inboundSchema;
  /** @deprecated use `PostcardCreateWithPDFFileFrom$outboundSchema` instead. */
  export const outboundSchema = PostcardCreateWithPDFFileFrom$outboundSchema;
  /** @deprecated use `PostcardCreateWithPDFFileFrom$Outbound` instead. */
  export type Outbound = PostcardCreateWithPDFFileFrom$Outbound;
}

export function postcardCreateWithPDFFileFromToJSON(
  postcardCreateWithPDFFileFrom: PostcardCreateWithPDFFileFrom,
): string {
  return JSON.stringify(
    PostcardCreateWithPDFFileFrom$outboundSchema.parse(
      postcardCreateWithPDFFileFrom,
    ),
  );
}

export function postcardCreateWithPDFFileFromFromJSON(
  jsonString: string,
): SafeParseResult<PostcardCreateWithPDFFileFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardCreateWithPDFFileFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardCreateWithPDFFileFrom' from JSON`,
  );
}

/** @internal */
export const PostcardCreateWithPDFFile$inboundSchema: z.ZodType<
  PostcardCreateWithPDFFile,
  z.ZodTypeDef,
  unknown
> = z.object({
  mergeVariables: z.record(z.any()).optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  sendDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  mailingClass: OrderMailingClass$inboundSchema.optional(),
  to: z.union([ContactCreate$inboundSchema, z.string()]),
  size: PostcardSize$inboundSchema,
  from: z.union([ContactCreate$inboundSchema, z.string()]).optional(),
  pdf: z.string(),
});

/** @internal */
export type PostcardCreateWithPDFFile$Outbound = {
  mergeVariables?: { [k: string]: any } | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  sendDate?: string | undefined;
  mailingClass?: string | undefined;
  to: ContactCreate$Outbound | string;
  size: string;
  from?: ContactCreate$Outbound | string | undefined;
  pdf: string;
};

/** @internal */
export const PostcardCreateWithPDFFile$outboundSchema: z.ZodType<
  PostcardCreateWithPDFFile$Outbound,
  z.ZodTypeDef,
  PostcardCreateWithPDFFile
> = z.object({
  mergeVariables: z.record(z.any()).optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  sendDate: z.date().transform(v => v.toISOString()).optional(),
  mailingClass: OrderMailingClass$outboundSchema.optional(),
  to: z.union([ContactCreate$outboundSchema, z.string()]),
  size: PostcardSize$outboundSchema,
  from: z.union([ContactCreate$outboundSchema, z.string()]).optional(),
  pdf: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardCreateWithPDFFile$ {
  /** @deprecated use `PostcardCreateWithPDFFile$inboundSchema` instead. */
  export const inboundSchema = PostcardCreateWithPDFFile$inboundSchema;
  /** @deprecated use `PostcardCreateWithPDFFile$outboundSchema` instead. */
  export const outboundSchema = PostcardCreateWithPDFFile$outboundSchema;
  /** @deprecated use `PostcardCreateWithPDFFile$Outbound` instead. */
  export type Outbound = PostcardCreateWithPDFFile$Outbound;
}

export function postcardCreateWithPDFFileToJSON(
  postcardCreateWithPDFFile: PostcardCreateWithPDFFile,
): string {
  return JSON.stringify(
    PostcardCreateWithPDFFile$outboundSchema.parse(postcardCreateWithPDFFile),
  );
}

export function postcardCreateWithPDFFileFromJSON(
  jsonString: string,
): SafeParseResult<PostcardCreateWithPDFFile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostcardCreateWithPDFFile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostcardCreateWithPDFFile' from JSON`,
  );
}
