/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Enum representing the supported postcard sizes.
 */
export const PostcardSize = {
  Sixx4: "6x4",
  Ninex6: "9x6",
  Elevenx6: "11x6",
} as const;
/**
 * Enum representing the supported postcard sizes.
 */
export type PostcardSize = ClosedEnum<typeof PostcardSize>;

/** @internal */
export const PostcardSize$inboundSchema: z.ZodNativeEnum<typeof PostcardSize> =
  z.nativeEnum(PostcardSize);

/** @internal */
export const PostcardSize$outboundSchema: z.ZodNativeEnum<typeof PostcardSize> =
  PostcardSize$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostcardSize$ {
  /** @deprecated use `PostcardSize$inboundSchema` instead. */
  export const inboundSchema = PostcardSize$inboundSchema;
  /** @deprecated use `PostcardSize$outboundSchema` instead. */
  export const outboundSchema = PostcardSize$outboundSchema;
}
