/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SelfMailerCreateWithHTML,
  SelfMailerCreateWithHTML$inboundSchema,
  SelfMailerCreateWithHTML$Outbound,
  SelfMailerCreateWithHTML$outboundSchema,
} from "./selfmailercreatewithhtml.js";
import {
  SelfMailerCreateWithPDFFile,
  SelfMailerCreateWithPDFFile$inboundSchema,
  SelfMailerCreateWithPDFFile$Outbound,
  SelfMailerCreateWithPDFFile$outboundSchema,
} from "./selfmailercreatewithpdffile.js";
import {
  SelfMailerCreateWithPDFURL,
  SelfMailerCreateWithPDFURL$inboundSchema,
  SelfMailerCreateWithPDFURL$Outbound,
  SelfMailerCreateWithPDFURL$outboundSchema,
} from "./selfmailercreatewithpdfurl.js";
import {
  SelfMailerCreateWithTemplate,
  SelfMailerCreateWithTemplate$inboundSchema,
  SelfMailerCreateWithTemplate$Outbound,
  SelfMailerCreateWithTemplate$outboundSchema,
} from "./selfmailercreatewithtemplate.js";

export type SelfMailerCreate =
  | SelfMailerCreateWithTemplate
  | SelfMailerCreateWithPDFURL
  | SelfMailerCreateWithPDFFile
  | SelfMailerCreateWithHTML;

/** @internal */
export const SelfMailerCreate$inboundSchema: z.ZodType<
  SelfMailerCreate,
  z.ZodTypeDef,
  unknown
> = z.union([
  SelfMailerCreateWithTemplate$inboundSchema,
  SelfMailerCreateWithPDFURL$inboundSchema,
  SelfMailerCreateWithPDFFile$inboundSchema,
  SelfMailerCreateWithHTML$inboundSchema,
]);

/** @internal */
export type SelfMailerCreate$Outbound =
  | SelfMailerCreateWithTemplate$Outbound
  | SelfMailerCreateWithPDFURL$Outbound
  | SelfMailerCreateWithPDFFile$Outbound
  | SelfMailerCreateWithHTML$Outbound;

/** @internal */
export const SelfMailerCreate$outboundSchema: z.ZodType<
  SelfMailerCreate$Outbound,
  z.ZodTypeDef,
  SelfMailerCreate
> = z.union([
  SelfMailerCreateWithTemplate$outboundSchema,
  SelfMailerCreateWithPDFURL$outboundSchema,
  SelfMailerCreateWithPDFFile$outboundSchema,
  SelfMailerCreateWithHTML$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailerCreate$ {
  /** @deprecated use `SelfMailerCreate$inboundSchema` instead. */
  export const inboundSchema = SelfMailerCreate$inboundSchema;
  /** @deprecated use `SelfMailerCreate$outboundSchema` instead. */
  export const outboundSchema = SelfMailerCreate$outboundSchema;
  /** @deprecated use `SelfMailerCreate$Outbound` instead. */
  export type Outbound = SelfMailerCreate$Outbound;
}

export function selfMailerCreateToJSON(
  selfMailerCreate: SelfMailerCreate,
): string {
  return JSON.stringify(
    SelfMailerCreate$outboundSchema.parse(selfMailerCreate),
  );
}

export function selfMailerCreateFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailerCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailerCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailerCreate' from JSON`,
  );
}
