/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ContactCreate,
  ContactCreate$inboundSchema,
  ContactCreate$Outbound,
  ContactCreate$outboundSchema,
} from "./contactcreate.js";
import {
  OrderMailingClass,
  OrderMailingClass$inboundSchema,
  OrderMailingClass$outboundSchema,
} from "./ordermailingclass.js";
import {
  SelfMailerSize,
  SelfMailerSize$inboundSchema,
  SelfMailerSize$outboundSchema,
} from "./selfmailersize.js";

/**
 * The recipient of this order. You can either supply the contact information inline here or provide a contact ID. PostGrid will automatically deduplicate contacts regardless of whether you provide the information inline here or call the contact creation endpoint.
 */
export type SelfMailerCreateWithPDFFileTo = ContactCreate | string;

/**
 * The contact information of the sender. You can pass contact information inline here just like you can for the `to`.
 */
export type SelfMailerCreateWithPDFFileFrom = ContactCreate | string;

export type SelfMailerCreateWithPDFFile = {
  /**
   * These will be merged with the variables in the template or HTML you create this order with. The keys in this object should match the variable names in the template _exactly_ as they are case-sensitive. Note that these _do not_ apply to PDFs uploaded with the order.
   */
  mergeVariables?: { [k: string]: any } | undefined;
  /**
   * An optional string describing this resource. Will be visible in the API and the dashboard.
   */
  description?: string | undefined;
  /**
   * See the section on Metadata.
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * This order will transition from `ready` to `printing` on the day after this date. You can use this parameter to schedule orders for a future date.
   */
  sendDate?: Date | undefined;
  /**
   * The mailing class of this order. If not provided, automatically set to `first_class`.
   */
  mailingClass?: OrderMailingClass | undefined;
  /**
   * The recipient of this order. You can either supply the contact information inline here or provide a contact ID. PostGrid will automatically deduplicate contacts regardless of whether you provide the information inline here or call the contact creation endpoint.
   */
  to: ContactCreate | string;
  /**
   * The size of the self-mailer.
   */
  size: SelfMailerSize;
  /**
   * The contact information of the sender. You can pass contact information inline here just like you can for the `to`.
   */
  from: ContactCreate | string;
  /**
   * A 2 page PDF file. The first page is the inside of the self-mailer and the second page is the outside (where the address will be stamped on).
   */
  pdf: string;
};

/** @internal */
export const SelfMailerCreateWithPDFFileTo$inboundSchema: z.ZodType<
  SelfMailerCreateWithPDFFileTo,
  z.ZodTypeDef,
  unknown
> = z.union([ContactCreate$inboundSchema, z.string()]);

/** @internal */
export type SelfMailerCreateWithPDFFileTo$Outbound =
  | ContactCreate$Outbound
  | string;

/** @internal */
export const SelfMailerCreateWithPDFFileTo$outboundSchema: z.ZodType<
  SelfMailerCreateWithPDFFileTo$Outbound,
  z.ZodTypeDef,
  SelfMailerCreateWithPDFFileTo
> = z.union([ContactCreate$outboundSchema, z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailerCreateWithPDFFileTo$ {
  /** @deprecated use `SelfMailerCreateWithPDFFileTo$inboundSchema` instead. */
  export const inboundSchema = SelfMailerCreateWithPDFFileTo$inboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFFileTo$outboundSchema` instead. */
  export const outboundSchema = SelfMailerCreateWithPDFFileTo$outboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFFileTo$Outbound` instead. */
  export type Outbound = SelfMailerCreateWithPDFFileTo$Outbound;
}

export function selfMailerCreateWithPDFFileToToJSON(
  selfMailerCreateWithPDFFileTo: SelfMailerCreateWithPDFFileTo,
): string {
  return JSON.stringify(
    SelfMailerCreateWithPDFFileTo$outboundSchema.parse(
      selfMailerCreateWithPDFFileTo,
    ),
  );
}

export function selfMailerCreateWithPDFFileToFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailerCreateWithPDFFileTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailerCreateWithPDFFileTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailerCreateWithPDFFileTo' from JSON`,
  );
}

/** @internal */
export const SelfMailerCreateWithPDFFileFrom$inboundSchema: z.ZodType<
  SelfMailerCreateWithPDFFileFrom,
  z.ZodTypeDef,
  unknown
> = z.union([ContactCreate$inboundSchema, z.string()]);

/** @internal */
export type SelfMailerCreateWithPDFFileFrom$Outbound =
  | ContactCreate$Outbound
  | string;

/** @internal */
export const SelfMailerCreateWithPDFFileFrom$outboundSchema: z.ZodType<
  SelfMailerCreateWithPDFFileFrom$Outbound,
  z.ZodTypeDef,
  SelfMailerCreateWithPDFFileFrom
> = z.union([ContactCreate$outboundSchema, z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailerCreateWithPDFFileFrom$ {
  /** @deprecated use `SelfMailerCreateWithPDFFileFrom$inboundSchema` instead. */
  export const inboundSchema = SelfMailerCreateWithPDFFileFrom$inboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFFileFrom$outboundSchema` instead. */
  export const outboundSchema = SelfMailerCreateWithPDFFileFrom$outboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFFileFrom$Outbound` instead. */
  export type Outbound = SelfMailerCreateWithPDFFileFrom$Outbound;
}

export function selfMailerCreateWithPDFFileFromToJSON(
  selfMailerCreateWithPDFFileFrom: SelfMailerCreateWithPDFFileFrom,
): string {
  return JSON.stringify(
    SelfMailerCreateWithPDFFileFrom$outboundSchema.parse(
      selfMailerCreateWithPDFFileFrom,
    ),
  );
}

export function selfMailerCreateWithPDFFileFromFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailerCreateWithPDFFileFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailerCreateWithPDFFileFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailerCreateWithPDFFileFrom' from JSON`,
  );
}

/** @internal */
export const SelfMailerCreateWithPDFFile$inboundSchema: z.ZodType<
  SelfMailerCreateWithPDFFile,
  z.ZodTypeDef,
  unknown
> = z.object({
  mergeVariables: z.record(z.any()).optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  sendDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  mailingClass: OrderMailingClass$inboundSchema.optional(),
  to: z.union([ContactCreate$inboundSchema, z.string()]),
  size: SelfMailerSize$inboundSchema,
  from: z.union([ContactCreate$inboundSchema, z.string()]),
  pdf: z.string(),
});

/** @internal */
export type SelfMailerCreateWithPDFFile$Outbound = {
  mergeVariables?: { [k: string]: any } | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  sendDate?: string | undefined;
  mailingClass?: string | undefined;
  to: ContactCreate$Outbound | string;
  size: string;
  from: ContactCreate$Outbound | string;
  pdf: string;
};

/** @internal */
export const SelfMailerCreateWithPDFFile$outboundSchema: z.ZodType<
  SelfMailerCreateWithPDFFile$Outbound,
  z.ZodTypeDef,
  SelfMailerCreateWithPDFFile
> = z.object({
  mergeVariables: z.record(z.any()).optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  sendDate: z.date().transform(v => v.toISOString()).optional(),
  mailingClass: OrderMailingClass$outboundSchema.optional(),
  to: z.union([ContactCreate$outboundSchema, z.string()]),
  size: SelfMailerSize$outboundSchema,
  from: z.union([ContactCreate$outboundSchema, z.string()]),
  pdf: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailerCreateWithPDFFile$ {
  /** @deprecated use `SelfMailerCreateWithPDFFile$inboundSchema` instead. */
  export const inboundSchema = SelfMailerCreateWithPDFFile$inboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFFile$outboundSchema` instead. */
  export const outboundSchema = SelfMailerCreateWithPDFFile$outboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFFile$Outbound` instead. */
  export type Outbound = SelfMailerCreateWithPDFFile$Outbound;
}

export function selfMailerCreateWithPDFFileToJSON(
  selfMailerCreateWithPDFFile: SelfMailerCreateWithPDFFile,
): string {
  return JSON.stringify(
    SelfMailerCreateWithPDFFile$outboundSchema.parse(
      selfMailerCreateWithPDFFile,
    ),
  );
}

export function selfMailerCreateWithPDFFileFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailerCreateWithPDFFile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailerCreateWithPDFFile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailerCreateWithPDFFile' from JSON`,
  );
}
