/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ContactCreate,
  ContactCreate$inboundSchema,
  ContactCreate$Outbound,
  ContactCreate$outboundSchema,
} from "./contactcreate.js";
import {
  OrderMailingClass,
  OrderMailingClass$inboundSchema,
  OrderMailingClass$outboundSchema,
} from "./ordermailingclass.js";
import {
  SelfMailerSize,
  SelfMailerSize$inboundSchema,
  SelfMailerSize$outboundSchema,
} from "./selfmailersize.js";

/**
 * The recipient of this order. You can either supply the contact information inline here or provide a contact ID. PostGrid will automatically deduplicate contacts regardless of whether you provide the information inline here or call the contact creation endpoint.
 */
export type SelfMailerCreateWithPDFURLTo = ContactCreate | string;

/**
 * The contact information of the sender. You can pass contact information inline here just like you can for the `to`.
 */
export type SelfMailerCreateWithPDFURLFrom = ContactCreate | string;

export type SelfMailerCreateWithPDFURL = {
  /**
   * These will be merged with the variables in the template or HTML you create this order with. The keys in this object should match the variable names in the template _exactly_ as they are case-sensitive. Note that these _do not_ apply to PDFs uploaded with the order.
   */
  mergeVariables?: { [k: string]: any } | undefined;
  /**
   * An optional string describing this resource. Will be visible in the API and the dashboard.
   */
  description?: string | undefined;
  /**
   * See the section on Metadata.
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * This order will transition from `ready` to `printing` on the day after this date. You can use this parameter to schedule orders for a future date.
   */
  sendDate?: Date | undefined;
  /**
   * The mailing class of this order. If not provided, automatically set to `first_class`.
   */
  mailingClass?: OrderMailingClass | undefined;
  /**
   * The recipient of this order. You can either supply the contact information inline here or provide a contact ID. PostGrid will automatically deduplicate contacts regardless of whether you provide the information inline here or call the contact creation endpoint.
   */
  to: ContactCreate | string;
  /**
   * The size of the self-mailer.
   */
  size: SelfMailerSize;
  /**
   * The contact information of the sender. You can pass contact information inline here just like you can for the `to`.
   */
  from: ContactCreate | string;
  /**
   * A URL pointing to a 2 page PDF file. The first page is the inside of the self-mailer and the second page is the outside (where the address will be stamped on).
   */
  pdf: string;
};

/** @internal */
export const SelfMailerCreateWithPDFURLTo$inboundSchema: z.ZodType<
  SelfMailerCreateWithPDFURLTo,
  z.ZodTypeDef,
  unknown
> = z.union([ContactCreate$inboundSchema, z.string()]);

/** @internal */
export type SelfMailerCreateWithPDFURLTo$Outbound =
  | ContactCreate$Outbound
  | string;

/** @internal */
export const SelfMailerCreateWithPDFURLTo$outboundSchema: z.ZodType<
  SelfMailerCreateWithPDFURLTo$Outbound,
  z.ZodTypeDef,
  SelfMailerCreateWithPDFURLTo
> = z.union([ContactCreate$outboundSchema, z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailerCreateWithPDFURLTo$ {
  /** @deprecated use `SelfMailerCreateWithPDFURLTo$inboundSchema` instead. */
  export const inboundSchema = SelfMailerCreateWithPDFURLTo$inboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFURLTo$outboundSchema` instead. */
  export const outboundSchema = SelfMailerCreateWithPDFURLTo$outboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFURLTo$Outbound` instead. */
  export type Outbound = SelfMailerCreateWithPDFURLTo$Outbound;
}

export function selfMailerCreateWithPDFURLToToJSON(
  selfMailerCreateWithPDFURLTo: SelfMailerCreateWithPDFURLTo,
): string {
  return JSON.stringify(
    SelfMailerCreateWithPDFURLTo$outboundSchema.parse(
      selfMailerCreateWithPDFURLTo,
    ),
  );
}

export function selfMailerCreateWithPDFURLToFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailerCreateWithPDFURLTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailerCreateWithPDFURLTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailerCreateWithPDFURLTo' from JSON`,
  );
}

/** @internal */
export const SelfMailerCreateWithPDFURLFrom$inboundSchema: z.ZodType<
  SelfMailerCreateWithPDFURLFrom,
  z.ZodTypeDef,
  unknown
> = z.union([ContactCreate$inboundSchema, z.string()]);

/** @internal */
export type SelfMailerCreateWithPDFURLFrom$Outbound =
  | ContactCreate$Outbound
  | string;

/** @internal */
export const SelfMailerCreateWithPDFURLFrom$outboundSchema: z.ZodType<
  SelfMailerCreateWithPDFURLFrom$Outbound,
  z.ZodTypeDef,
  SelfMailerCreateWithPDFURLFrom
> = z.union([ContactCreate$outboundSchema, z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailerCreateWithPDFURLFrom$ {
  /** @deprecated use `SelfMailerCreateWithPDFURLFrom$inboundSchema` instead. */
  export const inboundSchema = SelfMailerCreateWithPDFURLFrom$inboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFURLFrom$outboundSchema` instead. */
  export const outboundSchema = SelfMailerCreateWithPDFURLFrom$outboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFURLFrom$Outbound` instead. */
  export type Outbound = SelfMailerCreateWithPDFURLFrom$Outbound;
}

export function selfMailerCreateWithPDFURLFromToJSON(
  selfMailerCreateWithPDFURLFrom: SelfMailerCreateWithPDFURLFrom,
): string {
  return JSON.stringify(
    SelfMailerCreateWithPDFURLFrom$outboundSchema.parse(
      selfMailerCreateWithPDFURLFrom,
    ),
  );
}

export function selfMailerCreateWithPDFURLFromFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailerCreateWithPDFURLFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailerCreateWithPDFURLFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailerCreateWithPDFURLFrom' from JSON`,
  );
}

/** @internal */
export const SelfMailerCreateWithPDFURL$inboundSchema: z.ZodType<
  SelfMailerCreateWithPDFURL,
  z.ZodTypeDef,
  unknown
> = z.object({
  mergeVariables: z.record(z.any()).optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  sendDate: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  mailingClass: OrderMailingClass$inboundSchema.optional(),
  to: z.union([ContactCreate$inboundSchema, z.string()]),
  size: SelfMailerSize$inboundSchema,
  from: z.union([ContactCreate$inboundSchema, z.string()]),
  pdf: z.string(),
});

/** @internal */
export type SelfMailerCreateWithPDFURL$Outbound = {
  mergeVariables?: { [k: string]: any } | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  sendDate?: string | undefined;
  mailingClass?: string | undefined;
  to: ContactCreate$Outbound | string;
  size: string;
  from: ContactCreate$Outbound | string;
  pdf: string;
};

/** @internal */
export const SelfMailerCreateWithPDFURL$outboundSchema: z.ZodType<
  SelfMailerCreateWithPDFURL$Outbound,
  z.ZodTypeDef,
  SelfMailerCreateWithPDFURL
> = z.object({
  mergeVariables: z.record(z.any()).optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  sendDate: z.date().transform(v => v.toISOString()).optional(),
  mailingClass: OrderMailingClass$outboundSchema.optional(),
  to: z.union([ContactCreate$outboundSchema, z.string()]),
  size: SelfMailerSize$outboundSchema,
  from: z.union([ContactCreate$outboundSchema, z.string()]),
  pdf: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailerCreateWithPDFURL$ {
  /** @deprecated use `SelfMailerCreateWithPDFURL$inboundSchema` instead. */
  export const inboundSchema = SelfMailerCreateWithPDFURL$inboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFURL$outboundSchema` instead. */
  export const outboundSchema = SelfMailerCreateWithPDFURL$outboundSchema;
  /** @deprecated use `SelfMailerCreateWithPDFURL$Outbound` instead. */
  export type Outbound = SelfMailerCreateWithPDFURL$Outbound;
}

export function selfMailerCreateWithPDFURLToJSON(
  selfMailerCreateWithPDFURL: SelfMailerCreateWithPDFURL,
): string {
  return JSON.stringify(
    SelfMailerCreateWithPDFURL$outboundSchema.parse(selfMailerCreateWithPDFURL),
  );
}

export function selfMailerCreateWithPDFURLFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailerCreateWithPDFURL, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailerCreateWithPDFURL$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailerCreateWithPDFURL' from JSON`,
  );
}
