/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SelfMailerCreateWithTemplate = {
  /**
   * The template ID for the inside of the self-mailer. You can supply _either_ this or `insideHTML` but not both.
   */
  insideTemplate: string;
  /**
   * The template ID for the outside of the self-mailer. You can supply _either_ this or `outsideHTML` but not both.
   */
  outsideTemplate: string;
};

/** @internal */
export const SelfMailerCreateWithTemplate$inboundSchema: z.ZodType<
  SelfMailerCreateWithTemplate,
  z.ZodTypeDef,
  unknown
> = z.object({
  insideTemplate: z.string(),
  outsideTemplate: z.string(),
});

/** @internal */
export type SelfMailerCreateWithTemplate$Outbound = {
  insideTemplate: string;
  outsideTemplate: string;
};

/** @internal */
export const SelfMailerCreateWithTemplate$outboundSchema: z.ZodType<
  SelfMailerCreateWithTemplate$Outbound,
  z.ZodTypeDef,
  SelfMailerCreateWithTemplate
> = z.object({
  insideTemplate: z.string(),
  outsideTemplate: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SelfMailerCreateWithTemplate$ {
  /** @deprecated use `SelfMailerCreateWithTemplate$inboundSchema` instead. */
  export const inboundSchema = SelfMailerCreateWithTemplate$inboundSchema;
  /** @deprecated use `SelfMailerCreateWithTemplate$outboundSchema` instead. */
  export const outboundSchema = SelfMailerCreateWithTemplate$outboundSchema;
  /** @deprecated use `SelfMailerCreateWithTemplate$Outbound` instead. */
  export type Outbound = SelfMailerCreateWithTemplate$Outbound;
}

export function selfMailerCreateWithTemplateToJSON(
  selfMailerCreateWithTemplate: SelfMailerCreateWithTemplate,
): string {
  return JSON.stringify(
    SelfMailerCreateWithTemplate$outboundSchema.parse(
      selfMailerCreateWithTemplate,
    ),
  );
}

export function selfMailerCreateWithTemplateFromJSON(
  jsonString: string,
): SafeParseResult<SelfMailerCreateWithTemplate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelfMailerCreateWithTemplate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelfMailerCreateWithTemplate' from JSON`,
  );
}
