/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TemplateCreate = {
  /**
   * The HTML content of this template.
   */
  html?: string | undefined;
  /**
   * An optional string describing this resource. Will be visible in the API and the dashboard.
   */
  description?: string | undefined;
  /**
   * See the section on Metadata.
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const TemplateCreate$inboundSchema: z.ZodType<
  TemplateCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  html: z.string().optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
});

/** @internal */
export type TemplateCreate$Outbound = {
  html?: string | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const TemplateCreate$outboundSchema: z.ZodType<
  TemplateCreate$Outbound,
  z.ZodTypeDef,
  TemplateCreate
> = z.object({
  html: z.string().optional(),
  description: z.string().optional(),
  metadata: z.record(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TemplateCreate$ {
  /** @deprecated use `TemplateCreate$inboundSchema` instead. */
  export const inboundSchema = TemplateCreate$inboundSchema;
  /** @deprecated use `TemplateCreate$outboundSchema` instead. */
  export const outboundSchema = TemplateCreate$outboundSchema;
  /** @deprecated use `TemplateCreate$Outbound` instead. */
  export type Outbound = TemplateCreate$Outbound;
}

export function templateCreateToJSON(templateCreate: TemplateCreate): string {
  return JSON.stringify(TemplateCreate$outboundSchema.parse(templateCreate));
}

export function templateCreateFromJSON(
  jsonString: string,
): SafeParseResult<TemplateCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TemplateCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TemplateCreate' from JSON`,
  );
}
